// content_test.js — run: node content_test.js
var fs=require('fs');
var dataCode=fs.readFileSync('gamedata.js','utf8');
var code=fs.readFileSync('game.js','utf8');

global.window={_showDebug:false,GameSound:{play:function(){},init:function(){}},addEventListener:function(){}};
global.GameSound=global.window.GameSound;
global.self=global;
global.document={getElementById:function(id){
  if(id==='gameCanvas')return{width:960,height:640,
    getContext:function(){return{restore:function(){},save:function(){},translate:function(){},fillRect:function(){},
      fillText:function(){},strokeRect:function(){},beginPath:function(){},arc:function(){},
      fill:function(){},stroke:function(){},moveTo:function(){},lineTo:function(){},
      setLineDash:function(){},closePath:function(){},quadraticCurveTo:function(){},createRadialGradient:function(){return{addColorStop:function(){}}},
      scale:function(){},rotate:function(){},drawImage:function(){},globalAlpha:1,
      fillStyle:'',strokeStyle:'',lineWidth:1,font:'',textAlign:'left',shadowBlur:0,shadowColor:'',lineCap:'butt'}},
    addEventListener:function(){},focus:function(){},getBoundingClientRect:function(){return{left:0,top:0,width:960,height:640}}};
  return{style:{display:'none'},classList:{add:function(){},remove:function(){}},
    addEventListener:function(){},onclick:null,focus:function(){},offsetWidth:0,
    innerHTML:'',textContent:'',querySelectorAll:function(){return[]},closest:function(){return null}};
},readyState:'complete',addEventListener:function(e,f){f()},createElement:function(t){
  return{tagName:t,width:960,height:640,getContext:function(){return{fillRect:function(){},fillStyle:'',globalAlpha:1,beginPath:function(){},arc:function(){},fill:function(){},stroke:function(){}}}};
},querySelector:function(){return null}};
global.requestAnimationFrame=function(){};
global.setTimeout=function(f){f()};

(0,eval)(dataCode);
code=code.replace(/^\(function\(\)\{/,'');
code=code.replace(/\}\)\(\);?\s*$/,'');

code+='\n'+[
'var mockCtx={restore:function(){},save:function(){},translate:function(){},fillRect:function(){},',
'fillText:function(){},strokeRect:function(){},beginPath:function(){},arc:function(){},',
'fill:function(){},stroke:function(){},moveTo:function(){},lineTo:function(){},',
'setLineDash:function(){},closePath:function(){},quadraticCurveTo:function(){},createRadialGradient:function(){return{addColorStop:function(){}}},',
'scale:function(){},rotate:function(){},drawImage:function(){},globalAlpha:1,',
'fillStyle:"",strokeStyle:"",lineWidth:1,font:"",textAlign:"left",shadowBlur:0,shadowColor:"",lineCap:"butt"};',
'canvas={width:960,height:640,getContext:function(){return mockCtx},addEventListener:function(){},focus:function(){},',
'getBoundingClientRect:function(){return{left:0,top:0,width:960,height:640}}};',
'ctx=mockCtx;',

'var errors=[];',

// Test 37: New PREREQS
'try{var g=newGame("jian");startWave(g);var st=buildPickState(g);',
'  if(PREREQS.mogangyin(st))errors.push("37a: mogangyin should fail without judou/mojiaojin");',
'  if(PREREQS.houmo(st))errors.push("37b: houmo should fail with projSize=1 (threshold 1.2)");',
'  if(PREREQS.yanmoyan(st))errors.push("37c: yanmoyan should fail without yedeng");',
'  if(PREREQS.binghe(st))errors.push("37d: binghe should fail without liebing");',
'  if(PREREQS.lianhuanfu(st))errors.push("37e: lianhuanfu should fail without dieyin");',
'  if(PREREQS.molonglin(st))errors.push("37f: molonglin should fail without shixin");',
'  var judou=RELICS.find(function(r){return r.id==="judou"});',
'  g.relics.push(judou);judou.fn(g.player);var st2=buildPickState(g);',
'  if(!PREREQS.mogangyin(st2))errors.push("37g: mogangyin should pass with judou");',
'  if(!PREREQS.houmo(st2))errors.push("37h: houmo should pass with projSize>0.3");',
'}catch(e){errors.push("37: "+e.message)}',

// Test 38: projSize CAPS
'try{var g=newGame("bi");startWave(g);',
'  g.player.stats.projSize=3.5;g.player.atkCd=0;pAtk(g);',
'  if(!g.attacks.length)errors.push("38: no attack created at over-cap projSize");',
'}catch(e){errors.push("38: "+e.message)}',

// Test 39: 炎俑 fireTrail
'try{var g=newGame("jian");startWave(g);',
'  spawnEnemy(g,"yanyong",{noScale:true});var e=g.enemies[g.enemies.length-1];',
'  if(!e.fireTrail)errors.push("39a: fireTrail not set");',
'  if(e.hp!==95)errors.push("39b: wrong hp "+e.hp);',
'  e.spawnGraceT=0;var fBefore=g.fires.length;',
'  for(var i=0;i<25;i++)update(g);',
'  if(g.fires.length<=fBefore)errors.push("39c: no fires after 25 frames");',
'}catch(e){errors.push("39: "+e.message)}',

// Test 40: 速傀 stats
'try{var g=newGame("jian");startWave(g);',
'  spawnEnemy(g,"sukui",{noScale:true});var e=g.enemies[g.enemies.length-1];',
'  if(e.spd!==2.2)errors.push("40a: wrong spd "+e.spd);',
'  if(e.atkCd!==32)errors.push("40b: wrong atkCd "+e.atkCd);',
'  if(e.hp!==38)errors.push("40c: wrong hp "+e.hp);',
'}catch(e){errors.push("40: "+e.message)}',

// Test 41: Synergy chain
'try{var g=newGame("bi");startWave(g);var p=g.player;',
'  var judou=RELICS.find(function(r){return r.id==="judou"});',
'  var mogangyin=RELICS.find(function(r){return r.id==="mogangyin"});',
'  var houmo=RELICS.find(function(r){return r.id==="houmo"});',
'  judou.fn(p);var expectedPS=1.4;if(Math.abs(p.stats.projSize-expectedPS)>0.01)errors.push("41a: projSize="+p.stats.projSize+" expected ~"+expectedPS);',
'  mogangyin.fn(p);expectedPS=1.55;if(Math.abs(p.stats.projSize-expectedPS)>0.01)errors.push("41b: projSize="+p.stats.projSize+" expected ~"+expectedPS);',
'  if(Math.abs(p.slowOnHit-0.35)>0.01)errors.push("41c: slowOnHit="+p.slowOnHit);',
'  houmo.fn(p);expectedPS=1.65;if(Math.abs(p.stats.projSize-expectedPS)>0.01)errors.push("41d: projSize="+p.stats.projSize+" expected ~"+expectedPS);',
'  if(Math.abs(p.stats.dmg-1.2)>0.01)errors.push("41e: dmg="+p.stats.dmg+" expected ~1.2");',
'}catch(e){errors.push("41: "+e.message)}',

// Test 42: Fire budget
'try{var g=newGame("jian");startWave(g);',
'  for(var i=0;i<4;i++){spawnEnemy(g,"yanyong",{noScale:true});spawnEnemy(g,"fenling",{noScale:true})}',
'  g.enemies.forEach(function(e){e.spawnGraceT=0});',
'  for(var i=0;i<100;i++)update(g);',
'  if(g.fires.length>LIMITS.fires)errors.push("42: fires="+g.fires.length+">"+LIMITS.fires);',
'}catch(e){errors.push("42: "+e.message)}',

// Test 43: New curses
'try{["kuangxue","moyin"].forEach(function(cid){',
'  var g=newGame("jian");var c=CURSES.find(function(x){return x.id===cid});',
'  if(!c)errors.push("43a: curse "+cid+" not found");',
'  else{c.fn(g.player);startWave(g);for(var i=0;i<10;i++)update(g);}});',
'}catch(e){errors.push("43: "+e.message)}',

// Test 44: Death colors
'try{',
'  if(DEATH_COLOR.yanyong!=="fire")errors.push("44a: yanyong="+DEATH_COLOR.yanyong);',
'  if(DEATH_COLOR.sukui!=="ash")errors.push("44b: sukui="+DEATH_COLOR.sukui);',
'}catch(e){errors.push("44: "+e.message)}',

// Test 45: Enemy costs
'try{',
'  if(ENEMY_COST.yanyong<=1||ENEMY_COST.yanyong>=4)errors.push("45a: yanyong cost="+ENEMY_COST.yanyong);',
'  if(ENEMY_COST.sukui<=0.5||ENEMY_COST.sukui>=3)errors.push("45b: sukui cost="+ENEMY_COST.sukui);',
'}catch(e){errors.push("45: "+e.message)}',

// Test 46: PREREQS for remaining new relics
'try{var g=newGame("jian");startWave(g);var p=g.player;',
'  var yedeng=RELICS.find(function(r){return r.id==="yedeng"});yedeng.fn(p);g.relics.push(yedeng);',
'  var st=buildPickState(g);',
'  if(!PREREQS.yanmoyan(st))errors.push("46a: yanmoyan should pass with yedeng");',
'  var dieyin=RELICS.find(function(r){return r.id==="dieyin"});dieyin.fn(p);g.relics.push(dieyin);',
'  st=buildPickState(g);',
'  if(!PREREQS.lianhuanfu(st))errors.push("46b: lianhuanfu should pass with dieyin");',
'  var shixin=RELICS.find(function(r){return r.id==="shixin"});shixin.fn(p);g.relics.push(shixin);',
'  st=buildPickState(g);',
'  if(!PREREQS.molonglin(st))errors.push("46c: molonglin should pass with shixin");',
'  var liebing=RELICS.find(function(r){return r.id==="liebing"});liebing.fn(p);g.relics.push(liebing);',
'  st=buildPickState(g);',
'  if(!PREREQS.binghe(st))errors.push("46d: binghe should pass with liebing");',
'}catch(e){errors.push("46: "+e.message)}',

// Test 47: Mid-boss spawn (reduced HP, no bossKilled)
'try{var g=newGame("jian");',
'  spawnEnemy(g,"mojiangjun",{midBoss:true});var e=g.enemies[g.enemies.length-1];',
'  if(!e.midBoss)errors.push("47a: midBoss flag not set");',
'  if(!e.isBoss)errors.push("47b: isBoss should still be true");',
'  var bossHp=ETYPE.mojiangjun.hp;',
'  var expectedHp=Math.floor(bossHp*0.55);',
'  if(e.hp!==expectedHp)errors.push("47c: midBoss hp="+e.hp+" expected="+expectedHp+" (floor("+bossHp+"*0.55))");',
'  spawnEnemy(g,"mojiangjun",{});var e2=g.enemies[g.enemies.length-1];',
'  if(e2.midBoss)errors.push("47d: full boss should not have midBoss flag");',
'  var fullHp=Math.floor(bossHp);',
'  if(e2.hp!==fullHp)errors.push("47e: full boss hp="+e2.hp+" expected="+fullHp);',
'}catch(e){errors.push("47: "+e.message)}',

// Test 48: 毒蛛 duzhu
'try{',
'  if(!ETYPE.duzhu)errors.push("48a: duzhu not in ETYPE");',
'  else{if(!ETYPE.duzhu.poisonTrail)errors.push("48b: poisonTrail flag missing");',
'    if(ETYPE.duzhu.spd<1)errors.push("48c: spd too low");}',
'  if(!ENEMY_COST.duzhu)errors.push("48d: duzhu not in ENEMY_COST");',
'  if(DEATH_COLOR.duzhu!=="moss")errors.push("48e: duzhu death color="+DEATH_COLOR.duzhu);',
'  var g=newGame("jian");startWave(g);',
'  spawnEnemy(g,"duzhu",{noScale:true});var e=g.enemies[g.enemies.length-1];',
'  if(!e.poisonTrail)errors.push("48f: poisonTrail flag not set on instance");',
'  e.spawnGraceT=0;var fBefore=g.fires.length;',
'  for(var i=0;i<30;i++)update(g);',
'  var poisonFires=g.fires.filter(function(f){return f.poison});',
'  if(poisonFires.length===0)errors.push("48g: no poison fires after 30 frames");',
'}catch(e){errors.push("48: "+e.message)}',

// Test 49: New relics (mojiangling/guishouyin/zhiyanwen)
'try{',
'  var ids=["mojiangling","guishouyin","zhiyanwen"];',
'  ids.forEach(function(rid){',
'    var r=RELICS.find(function(x){return x.id===rid});',
'    if(!r)errors.push("49a: relic "+rid+" not found in RELICS");',
'    else{if(!r.tags||r.tags.length<1)errors.push("49b: "+rid+" missing tags");',
'      if(!r.fn)errors.push("49c: "+rid+" missing fn");}',
'  });',
'  var g=newGame("bi");startWave(g);var p=g.player;',
'  var mjl=RELICS.find(function(r){return r.id==="mojiangling"});mjl.fn(p);',
'  if(!p.eliteKillBurst)errors.push("49d: eliteKillBurst not set");',
'  var gsy=RELICS.find(function(r){return r.id==="guishouyin"});gsy.fn(p);',
'  if(!p.dodgeSoulGrab)errors.push("49e: dodgeSoulGrab not set");',
'  var zyw=RELICS.find(function(r){return r.id==="zhiyanwen"});zyw.fn(p);',
'  if(!p.projSlowField)errors.push("49f: projSlowField not set");',
'}catch(e){errors.push("49: "+e.message)}',

// Test 50: duzhu in WAVE_TIERS
'try{',
'  var hasDuzu=false;WAVE_TIERS.forEach(function(tier){if(tier.indexOf("duzhu")>=0)hasDuzu=true});',
'  if(!hasDuzu)errors.push("50a: duzhu not in any WAVE_TIERS");',
'}catch(e){errors.push("50: "+e.message)}',

// Test 51: 蛊师 gushi
'try{',
'  if(!ETYPE.gushi)errors.push("51a: gushi not in ETYPE");',
'  else{if(!ETYPE.gushi.buffAura)errors.push("51b: buffAura flag missing");',
'    if(ETYPE.gushi.dmg!==0)errors.push("51c: gushi should have dmg=0 (support unit)");}',
'  if(!ENEMY_COST.gushi)errors.push("51d: gushi not in ENEMY_COST");',
'  if(DEATH_COLOR.gushi!=="boss")errors.push("51e: gushi death color="+DEATH_COLOR.gushi);',
'  var hasGushi=false;WAVE_TIERS.forEach(function(tier){if(tier.indexOf("gushi")>=0)hasGushi=true});',
'  if(!hasGushi)errors.push("51f: gushi not in any WAVE_TIERS");',
'  var g=newGame("jian");startWave(g);spawnEnemy(g,"gushi",{noScale:true});',
'  var e=g.enemies[g.enemies.length-1];if(!e.buffAura)errors.push("51g: buffAura not set on instance");',
'}catch(e){errors.push("51: "+e.message)}',

// Test 52: New curses (miwu/guihuo)
'try{["miwu","guihuo"].forEach(function(cid){',
'  var c=CURSES.find(function(x){return x.id===cid});',
'  if(!c)errors.push("52a: curse "+cid+" not found");',
'  else{c.fn(g.player);var g2=newGame("jian");c.fn(g2.player);',
'    if(cid==="miwu"&&!g2.player.fogCurse)errors.push("52b: miwu fogCurse not set");',
'    if(cid==="guihuo"&&!g2.player.soulOrbCurse)errors.push("52c: guihuo soulOrbCurse not set");}})',
'}catch(e){errors.push("52: "+e.message)}',

// Test 53: New relics round 2 (shiguping/yexingyi/hunsuolian)
'try{',
'  var ids=["shiguping","yexingyi","hunsuolian"];',
'  ids.forEach(function(rid){',
'    var r=RELICS.find(function(x){return x.id===rid});',
'    if(!r)errors.push("53a: relic "+rid+" not found");',
'    else{if(!r.fn)errors.push("53b: "+rid+" missing fn");}',
'  });',
'  var g=newGame("jian");var p=g.player;',
'  var sgp=RELICS.find(function(r){return r.id==="shiguping"});sgp.fn(p);',
'  if(!p.poisonHeal)errors.push("53c: poisonHeal not set");',
'  var yxy=RELICS.find(function(r){return r.id==="yexingyi"});yxy.fn(p);',
'  if(!p.fogBonus)errors.push("53d: fogBonus not set");',
'  if(!p.soulOrbHeal)errors.push("53e: soulOrbHeal not set");',
'  var hsl=RELICS.find(function(r){return r.id==="hunsuolian"});hsl.fn(p);',
'  if(!p.comboDmgBonus)errors.push("53f: comboDmgBonus not set");',
'}catch(e){errors.push("53: "+e.message)}',

// Test 54: Stage hazards exist and are valid
'try{',
'  if(!STAGE_HAZARDS||STAGE_HAZARDS.length!==6)errors.push("54a: STAGE_HAZARDS should have 6 entries");',
'  else{STAGE_HAZARDS.forEach(function(h){',
'    if(!h.id||!h.name||!h.desc||!h.interval)errors.push("54b: hazard "+h.id+" incomplete");',
'    if(h.interval<30)errors.push("54c: hazard "+h.id+" interval too short");});}',
'}catch(e){errors.push("54: "+e.message)}',

// Test 55: 墨灵玉 relic + ink spirit spawn
'try{var g=newGame("bi");startWave(g);var p=g.player;',
'  g.announceT=0;',
'  var mly=RELICS.find(function(r){return r.id==="molingyu"});',
'  if(!mly)errors.push("55a: molingyu not found");',
'  else{mly.fn(p);',
'    if(!p.hasInkSpirit)errors.push("55b: hasInkSpirit not set");',
'    if(p.inkSpiritCount<1)errors.push("55c: inkSpiritCount not set");',
'    for(var i=0;i<10;i++)update(g);',
'    if(g.inkSpirits.length===0)errors.push("55d: no spirit spawned after 10 frames");',
'    if(g.inkSpirits.length!==p.inkSpiritCount)errors.push("55e: spirit count mismatch "+g.inkSpirits.length+"/"+p.inkSpiritCount);}',
'}catch(e){errors.push("55: "+e.message)}',

// Test 56: 画皮 mimic disguise and reveal
'try{',
'  if(!ETYPE.huapi)errors.push("56a: huapi not in ETYPE");',
'  else{if(!ETYPE.huapi.mimic)errors.push("56b: mimic flag missing");',
'    if(ETYPE.huapi.spd<1.5)errors.push("56c: spd too low for ambusher");}',
'  if(!ENEMY_COST.huapi)errors.push("56d: huapi not in ENEMY_COST");',
'  if(DEATH_COLOR.huapi!=="accent")errors.push("56e: death color="+DEATH_COLOR.huapi);',
'  var hasHuapi=false;WAVE_TIERS.forEach(function(t){if(t.indexOf("huapi")>=0)hasHuapi=true});',
'  if(!hasHuapi)errors.push("56f: huapi not in WAVE_TIERS");',
'  var g=newGame("jian");startWave(g);',
'  spawnEnemy(g,"huapi",{noScale:true});var e=g.enemies[g.enemies.length-1];',
'  if(!e.mimic)errors.push("56g: mimic flag not set");',
'  if(!e.disguised)errors.push("56h: disguised flag not set");',
'  // Move player close to reveal mimic',
'  g.player.x=e.x+10;g.player.y=e.y+10;',
'  for(var i=0;i<5;i++)update(g);',
'  if(e.disguised&&dstSq(e,g.player)<50*50)errors.push("56i: mimic should reveal when close");',
'}catch(e){errors.push("56: "+e.message)}',

// Test 57: 墨蛭 leech attach and detach
'try{',
'  if(!ETYPE.mozhi)errors.push("57a: mozhi not in ETYPE");',
'  else{if(!ETYPE.mozhi.leech)errors.push("57b: leech flag missing");',
'    if(ETYPE.mozhi.dmg!==0)errors.push("57c: leech should have dmg=0");}',
'  if(!ENEMY_COST.mozhi)errors.push("57d: mozhi not in ENEMY_COST");',
'  var hasMozhi=false;WAVE_TIERS.forEach(function(t){if(t.indexOf("mozhi")>=0)hasMozhi=true});',
'  if(!hasMozhi)errors.push("57e: mozhi not in WAVE_TIERS");',
'  var g=newGame("jian");startWave(g);var p=g.player;',
'  spawnEnemy(g,"mozhi",{noScale:true});var e=g.enemies[g.enemies.length-1];',
'  if(!e.leech)errors.push("57f: leech flag not set");',
'  if(e.attached)errors.push("57g: should not start attached");',
'  e.spawnGraceT=0;e.x=p.x+5;e.y=p.y+5;p.invTimer=0;',
'  for(var i=0;i<3;i++)update(g);',
'  if(!e.attached&&collideSq(e,p,2))errors.push("57h: leech should attach on contact");',
'  if(p.leeches.length>0){',
'    var hpBefore=p.hp;',
'    // Dash to detach',
'    startDodge(g,1,0);for(var i=0;i<5;i++)update(g);',
'    if(p.leeches.length>0)errors.push("57i: leech should detach on dodge");}',
'}catch(e){errors.push("57: "+e.message)}',

// Test 58: 墨灵契 relic (spirit dmg bonus)
'try{',
'  var g=newGame("bi");startWave(g);var p=g.player;',
'  var mly=RELICS.find(function(r){return r.id==="molingyu"});mly.fn(p);',
'  var mlq=RELICS.find(function(r){return r.id==="molingqi"});',
'  if(!mlq)errors.push("58a: molingqi not found");',
'  else{mlq.fn(p);',
'    if(p.inkSpiritCount<3)errors.push("58b: spirit count should be >=3 after both relics, got "+p.inkSpiritCount);',
'    if(!p.spiritDmgBonus||p.spiritDmgBonus<0.4)errors.push("58c: spiritDmgBonus not set or too low");}',
'  g.announceT=0;',
'  for(var i=0;i<10;i++)update(g);',
'  if(g.inkSpirits.length<3)errors.push("58d: not enough spirits spawned: "+g.inkSpirits.length);',
'}catch(e){errors.push("58: "+e.message)}',

// Test 59: 破妄瞳 relic (mimic first crit)
'try{',
'  var g=newGame("jian");startWave(g);var p=g.player;',
'  var pwt=RELICS.find(function(r){return r.id==="powangtong"});',
'  if(!pwt)errors.push("59a: powangtong not found");',
'  else{pwt.fn(p);',
'    if(!p.mimicFirstCrit)errors.push("59b: mimicFirstCrit not set");',
'    if(p.stats.critRate<0.24)errors.push("59c: critRate not increased");}',
'}catch(e){errors.push("59: "+e.message)}',

// Test 60: 蛭反 relic (leech buff)
'try{',
'  var g=newGame("jian");startWave(g);var p=g.player;',
'  var zf=RELICS.find(function(r){return r.id==="zhifan"});',
'  if(!zf)errors.push("60a: zhifan not found");',
'  else{zf.fn(p);',
'    if(!p.leechBuff)errors.push("60b: leechBuff not set");}',
'}catch(e){errors.push("60: "+e.message)}',

// Test 61: 灵噬 curse (spirit HP cost)
'try{',
'  var c=CURSES.find(function(x){return x.id==="lingshi"});',
'  if(!c)errors.push("61a: lingshi curse not found");',
'  else{var g2=newGame("jian");c.fn(g2.player);',
'    if(!g2.player.spiritHpCost)errors.push("61b: spiritHpCost not set");',
'    if(!g2.player.spiritDmgBonus||g2.player.spiritDmgBonus<0.9)errors.push("61c: spiritDmgBonus too low");}',
'}catch(e){errors.push("61: "+e.message)}',

// Test 62: molingqi PREREQ
'try{',
'  var g=newGame("bi");startWave(g);var st=buildPickState(g);',
'  if(PREREQS.molingqi(st))errors.push("62a: molingqi should fail without molingyu");',
'  var mly=RELICS.find(function(r){return r.id==="molingyu"});mly.fn(g.player);g.relics.push(mly);',
'  st=buildPickState(g);',
'  if(!PREREQS.molingqi(st))errors.push("62b: molingqi should pass with molingyu");',
'}catch(e){errors.push("62: "+e.message)}',

// Test 63: 墨守阵 defFormation trigger + damage reduction
'try{',
'  var g=newGame("jian");startWave(g);var p=g.player;g.announceT=0;',
'  var msz=RELICS.find(function(r){return r.id==="moshouzhen"});',
'  if(!msz)errors.push("63a: moshouzhen not found");',
'  else{msz.fn(p);',
'    if(!p.defFormation)errors.push("63b: defFormation not set");',
'    // Simulate standing still for 60 frames',
'    for(var i=0;i<65;i++){update(g);}',
'    if(g.formations.length===0)errors.push("63c: no def formation after 65 still frames");',
'    else{var fm=g.formations[0];if(fm.type!=="def")errors.push("63d: wrong formation type");',
'      if(fm.r<40)errors.push("63e: def formation too small r="+fm.r);}',
'  }',
'}catch(e){errors.push("63: "+e.message)}',

// Test 64: 墨攻阵 atkFormation trigger
'try{',
'  var g=newGame("jian");startWave(g);var p=g.player;g.announceT=0;',
'  var mgz=RELICS.find(function(r){return r.id==="mogongzhen"});',
'  if(!mgz)errors.push("64a: mogongzhen not found");',
'  else{mgz.fn(p);',
'    if(!p.atkFormation)errors.push("64b: atkFormation not set");',
'    // Kill 3 enemies to trigger',
'    p.atkFormCount=3;update(g);',
'    var atkForm=g.formations.filter(function(f){return f.type==="atk"});',
'    if(atkForm.length===0)errors.push("64c: no atk formation after 3 kills");}',
'}catch(e){errors.push("64: "+e.message)}',

// Test 65: 墨童 motong deathBomb
'try{',
'  if(!ETYPE.motong)errors.push("65a: motong not in ETYPE");',
'  else{if(!ETYPE.motong.deathBomb)errors.push("65b: deathBomb flag missing");',
'    if(ETYPE.motong.deathBombDelay<30)errors.push("65c: bomb delay too short");}',
'  if(!ENEMY_COST.motong)errors.push("65d: motong not in ENEMY_COST");',
'  var hasMotong=false;WAVE_TIERS.forEach(function(t){if(t.indexOf("motong")>=0)hasMotong=true});',
'  if(!hasMotong)errors.push("65e: motong not in WAVE_TIERS");',
'  var g=newGame("jian");startWave(g);',
'  spawnEnemy(g,"motong",{noScale:true});var e=g.enemies[g.enemies.length-1];',
'  if(!e.deathBomb)errors.push("65f: deathBomb flag not set on instance");',
'  e.hp=1;damageEnemy(g,e,10,"test");',
'  if(!g.pendingDeathbursts||g.pendingDeathbursts.length===0)errors.push("65g: no deathburst spawned");',
'  else{var db=g.pendingDeathbursts[0];if(db.type!=="motong")errors.push("65h: wrong burst type");',
'    if(!db.maxTimer)errors.push("65i: maxTimer not set");}',
'}catch(e){errors.push("65: "+e.message)}',

// Test 66: 阵眼 formBoost synergy
'try{',
'  var g=newGame("jian");startWave(g);var p=g.player;',
'  var zy=RELICS.find(function(r){return r.id==="zhenyan"});',
'  if(!zy)errors.push("66a: zhenyan not found");',
'  else{zy.fn(p);',
'    if(!p.formBoost)errors.push("66b: formBoost not set");}',
'}catch(e){errors.push("66: "+e.message)}',

// Test 67: 墨竭 curse double formation
'try{',
'  var c=CURSES.find(function(x){return x.id==="mojie"});',
'  if(!c)errors.push("67a: mojie curse not found");',
'  else{var g2=newGame("jian");c.fn(g2.player);',
'    if(!g2.player.formDouble)errors.push("67b: formDouble not set");',
'    if(g2.player.maxHpOverride!==75)errors.push("67c: maxHpOverride should be 75");}',
'}catch(e){errors.push("67: "+e.message)}',

// Test 68: 阵眼 PREREQ
'try{',
'  var g=newGame("bi");startWave(g);var st=buildPickState(g);',
'  if(PREREQS.zhenyan(st))errors.push("68a: zhenyan should fail without any formation relic");',
'  var msz=RELICS.find(function(r){return r.id==="moshouzhen"});msz.fn(g.player);g.relics.push(msz);',
'  st=buildPickState(g);',
'  if(!PREREQS.zhenyan(st))errors.push("68b: zhenyan should pass with moshouzhen");',
'}catch(e){errors.push("68: "+e.message)}',

// Test 69: 墨镜 relic - reflectChance and reflectDmgMult
'try{',
'  var mj=RELICS.find(function(r){return r.id==="mojing"});',
'  if(!mj)errors.push("69a: mojing not found");',
'  else{var g69=newGame("jian");mj.fn(g69.player);',
'    if(g69.player.reflectChance!==0.3)errors.push("69b: reflectChance should be 0.3, got "+g69.player.reflectChance);',
'    if(g69.player.reflectDmgMult!==1)errors.push("69c: reflectDmgMult should be 1, got "+g69.player.reflectDmgMult);}',
'}catch(e){errors.push("69: "+e.message)}',

// Test 70: 回春阵 relic - healFormation flag
'try{',
'  var hcz=RELICS.find(function(r){return r.id==="huichunzhen"});',
'  if(!hcz)errors.push("70a: huichunzhen not found");',
'  else{var g70=newGame("jian");hcz.fn(g70.player);',
'    if(!g70.player.healFormation)errors.push("70b: healFormation not set");}',
'}catch(e){errors.push("70: "+e.message)}',

// Test 71: 墨涡 relic - vortexOnKill flag
'try{',
'  var mw=RELICS.find(function(r){return r.id==="mowo"});',
'  if(!mw)errors.push("71a: mowo not found");',
'  else{var g71=newGame("jian");mw.fn(g71.player);',
'    if(!g71.player.vortexOnKill)errors.push("71b: vortexOnKill not set");}',
'}catch(e){errors.push("71: "+e.message)}',

// Test 72: 墨蝠 enemy - swoop flag on instance
'try{',
'  if(!ETYPE.mofu)errors.push("72a: mofu not in ETYPE");',
'  else{if(!ETYPE.mofu.swoop)errors.push("72b: swoop flag not on ETYPE");',
'    var g72=newGame("jian");startWave(g72);',
'    spawnEnemy(g72,"mofu",{noScale:true});var e72=g72.enemies[g72.enemies.length-1];',
'    if(!e72.swoop)errors.push("72c: swoop flag not set on instance");',
'    if(e72.swoopPrep!==35)errors.push("72d: swoopPrep should be 35");}',
'}catch(e){errors.push("72: "+e.message)}',

// Test 73: 墨瘴 hazard - exists in STAGE_HAZARDS
'try{',
'  var mz=STAGE_HAZARDS.find(function(h){return h.id==="mozhang"});',
'  if(!mz)errors.push("73a: mozhang not in STAGE_HAZARDS");',
'  else{if(mz.interval!==200)errors.push("73b: interval should be 200");}',
'}catch(e){errors.push("73: "+e.message)}',

// Test 74: 回春阵 PREREQ - requires formation relic
'try{',
'  var g74=newGame("bi");startWave(g74);var st74=buildPickState(g74);',
'  if(PREREQS.huichunzhen(st74))errors.push("74a: should fail without formation relic");',
'  var msz=RELICS.find(function(r){return r.id==="moshouzhen"});msz.fn(g74.player);g74.relics.push(msz);',
'  st74=buildPickState(g74);',
'  if(!PREREQS.huichunzhen(st74))errors.push("74b: should pass with moshouzhen");',
'}catch(e){errors.push("74: "+e.message)}',

// Test 75: 墨镜 projectile reflection - hurtP bypass on reflect
'try{',
'  var g75=newGame("jian");startWave(g75);var p75=g75.player;',
'  var mj75=RELICS.find(function(r){return r.id==="mojing"});mj75.fn(p75);',
'  if(p75.reflectChance!==0.3)errors.push("75a: reflect not set");',
'  p75.invTimer=0;',
'  g75.eProj.push({x:p75.x+10,y:p75.y,vx:-3,vy:0,life:40,dmg:10,r:5,_src:{name:"test"}});',
'  p75.reflectChance=1.0;',
'  var ep=g75.eProj[0];',
'  var mr=ep.r+p75.r;',
'  if(dstSq(ep,p75)<mr*mr&&p75.invTimer<=0){',
'    if(Math.random()<p75.reflectChance){',
'      ep.vx*=-1;ep.vy*=-1;ep.dmg=Math.floor(ep.dmg*(1+p75.reflectDmgMult));',
'      g75.attacks.push({x:ep.x,y:ep.y,vx:ep.vx,vy:ep.vy,life:ep.life,dmg:ep.dmg,r:5,type:"proj"});',
'      g75.eProj.splice(0,1);',
'    }',
'  }',
'  if(g75.eProj.length!==0)errors.push("75b: eProj should be removed on reflect");',
'  if(g75.attacks.length===0)errors.push("75c: reflected attack not created");',
'  else{if(g75.attacks[0].dmg!==20)errors.push("75d: reflected dmg should be 20 (10*2), got "+g75.attacks[0].dmg);}',
'}catch(e){errors.push("75: "+e.message)}',

// Test 76: 墨涡 vortex kill counting
'try{',
'  var g76=newGame("jian");startWave(g76);var p76=g76.player;',
'  var mw76=RELICS.find(function(r){return r.id==="mowo"});mw76.fn(p76);',
'  if(!p76.vortexOnKill)errors.push("76a: vortexOnKill not set");',
'  if((p76.vortexKills||0)!==0)errors.push("76b: vortexKills should start at 0");',
'  p76.vortexKills=5;',
'  // Simulate vortex trigger in update',
'  if(p76.vortexOnKill&&(p76.vortexKills||0)>=5){',
'    p76.vortexKills=0;',
'    g76.formations.push({x:p76.x,y:p76.y,r:90,life:40,maxLife:40,type:"vortex",dmg:Math.floor(g76.weapon.dmg*p76.stats.dmg*1.5)});',
'  }',
'  if(p76.vortexKills!==0)errors.push("76c: vortexKills should reset after trigger");',
'  if(g76.formations.length===0)errors.push("76d: vortex formation not created");',
'  else{if(g76.formations[0].type!=="vortex")errors.push("76e: wrong formation type");}',
'}catch(e){errors.push("76: "+e.message)}',

// Test 78: 墨甲 relic - formDef flag
'try{',
'  var mja=RELICS.find(function(r){return r.id==="mojia"});',
'  if(!mja)errors.push("78a: mojia not found");',
'  else{var g78=newGame("jian");var def78=g78.player.stats.def;mja.fn(g78.player);',
'    if(!g78.player.formDef)errors.push("78b: formDef not set");',
'    if(g78.player.stats.def!==def78+0.15)errors.push("78c: def should increase by 0.15");}',
'}catch(e){errors.push("78: "+e.message)}',

// Test 77: 墨吸 relic - formationLeech flag
'try{',
'  var mx77=RELICS.find(function(r){return r.id==="moxi"});',
'  if(!mx77)errors.push("77a: moxi not found");',
'  else{var g77=newGame("jian");mx77.fn(g77.player);',
'    if(!g77.player.formationLeech)errors.push("77b: formationLeech not set");',
'    g77.formations.push({x:400,y:300,r:50,life:20,maxLife:90,type:"def"});',
'    var preLife=g77.formations[0].life;',
'    g77.player.formationLeech=true;',
'    g77.formations.forEach(function(fm){fm.life=Math.min(fm.maxLife,fm.life+15)});',
'    if(g77.formations[0].life!==35)errors.push("77c: life should extend to 35, got "+g77.formations[0].life);',
'    g77.formations.forEach(function(fm){fm.life=Math.min(fm.maxLife,fm.life+15)});',
'    if(g77.formations[0].life!==50)errors.push("77d: life should extend to 50");}',
'}catch(e){errors.push("77: "+e.message)}',

'// --- v2.12: 墨爆 / 墨弦 / 墨蝶 ---',

'// Test 79: mobao relic - formationDetonate flag',
'try{',
'  var g79=newGame("jian");var r79=RELICS.find(function(r){return r.id==="mobao"});',
'  if(!r79)errors.push("79a: mobao not found");',
'  else{r79.fn(g79.player);',
'    if(!g79.player.formationDetonate)errors.push("79b: formationDetonate not set");}',
'}catch(e){errors.push("79: "+e.message)}',

'// Test 80: moxian relic - inkStrings flag',
'try{',
'  var g80=newGame("jian");var r80=RELICS.find(function(r){return r.id==="moxian"});',
'  if(!r80)errors.push("80a: moxian not found");',
'  else{r80.fn(g80.player);',
'    if(!g80.player.inkStrings)errors.push("80b: inkStrings not set");}',
'}catch(e){errors.push("80: "+e.message)}',

'// Test 81: modie enemy type',
'try{',
'  var md=ETYPE.modie;',
'  if(!md)errors.push("81a: modie not in ETYPE");',
'  else{if(md.name!=="墨蝶")errors.push("81b: modie name mismatch");',
'    if(!md.deathBuff)errors.push("81c: modie missing deathBuff");',
'    if(md.deathBuffR!==130)errors.push("81d: deathBuffR should be 130");',
'    if(md.deathBuffT!==180)errors.push("81e: deathBuffT should be 180");}',
'}catch(e){errors.push("81: "+e.message)}',

'// Test 82: modie in enemy tables',
'try{',
'  if(!DEATH_COLOR.modie)errors.push("82a: modie missing from DEATH_COLOR");',
'  if(!ENEMY_COST.modie)errors.push("82b: modie missing from ENEMY_COST");',
'  if(WAVE_TIERS[1].indexOf("modie")<0)errors.push("82c: modie missing from WAVE_TIERS[1]");',
'}catch(e){errors.push("82: "+e.message)}',

'// Test 83: mobao PREREQ',
'try{',
'  if(!PREREQS.mobao)errors.push("83a: mobao PREREQ not found");',
'  else{var s83a={ownedIds:{}};',
'    if(PREREQS.mobao(s83a))errors.push("83b: should fail without formation relic");',
'    var s83b={ownedIds:{moshouzhen:true}};',
'    if(!PREREQS.mobao(s83b))errors.push("83c: should pass with moshouzhen");',
'    var s83c={ownedIds:{mowo:true}};',
'    if(!PREREQS.mobao(s83c))errors.push("83d: should pass with mowo");}',
'}catch(e){errors.push("83: "+e.message)}',

'// Test 84: moxian PREREQ (needs 2+ formation relics)',
'try{',
'  if(!PREREQS.moxian)errors.push("84a: moxian PREREQ not found");',
'  else{var s84a={ownedIds:{moshouzhen:true}};',
'    if(PREREQS.moxian(s84a))errors.push("84b: should fail with only 1 formation relic");',
'    var s84b={ownedIds:{moshouzhen:true,mogongzhen:true}};',
'    if(!PREREQS.moxian(s84b))errors.push("84c: should pass with 2 formation relics");',
'    var s84c={ownedIds:{moshouzhen:true,mobao:true}};',
'    if(!PREREQS.moxian(s84c))errors.push("84d: should pass with moshouzhen+mobao");}',
'}catch(e){errors.push("84: "+e.message)}',

'// Test 85: modie deathBuff initializes on spawned enemy',
'try{',
'  var g85=newGame("jian");g85.player.x=400;g85.player.y=300;',
'  spawnEnemy(g85,"modie",{});',
'  var e85=g85.enemies[g85.enemies.length-1];',
'  if(!e85||e85.type!=="modie")errors.push("85a: modie not spawned");',
'  else{if(!e85.deathBuff)errors.push("85b: deathBuff not on instance");',
'    if(e85.deathBuffR!==130)errors.push("85c: deathBuffR not 130 on instance");',
'    if(!e85.ranged)errors.push("85d: modie should be ranged");}',
'}catch(e){errors.push("85: "+e.message)}',

'// --- v2.13: 墨钉 / 墨澄 ---',

'// Test 86: moding relic - attackPin flag',
'try{',
'  var g86=newGame("jian");var r86=RELICS.find(function(r){return r.id==="moding"});',
'  if(!r86)errors.push("86a: moding not found");',
'  else{r86.fn(g86.player);',
'    if(!g86.player.attackPin)errors.push("86b: attackPin not set");}',
'}catch(e){errors.push("86: "+e.message)}',

'// Test 87: mochen relic - formClarity flag',
'try{',
'  var g87=newGame("jian");var r87=RELICS.find(function(r){return r.id==="mochen"});',
'  if(!r87)errors.push("87a: mochen not found");',
'  else{r87.fn(g87.player);',
'    if(!g87.player.formClarity)errors.push("87b: formClarity not set");}',
'}catch(e){errors.push("87: "+e.message)}',

'// Test 88: moding PREREQ (melee weapon only)',
'try{',
'  if(!PREREQS.moding)errors.push("88a: moding PREREQ not found");',
'  else{var s88a={weaponType:"ranged"};',
'    if(PREREQS.moding(s88a))errors.push("88b: should fail with ranged weapon");',
'    var s88b={weaponType:"melee"};',
'    if(!PREREQS.moding(s88b))errors.push("88c: should pass with melee weapon");}',
'}catch(e){errors.push("88: "+e.message)}',

'// Test 89: moding pins enemies on damage',
'try{',
'  var g89=newGame("jian");g89.player.attackPin=true;',
'  spawnEnemy(g89,"zhikui",{});',
'  var e89=g89.enemies[g89.enemies.length-1];e89.hp=50;',
'  damageEnemy(g89,e89,10,"hit");',
'  if(!e89.pinned||e89.pinned<=0)errors.push("89a: enemy not pinned after damage");',
'  if(e89.pinned>30)errors.push("89b: pinned too long: "+e89.pinned);',
'}catch(e){errors.push("89: "+e.message)}',

'// Test 90: motao relic - killPulse flag',
'try{',
'  var g90=newGame("jian");var r90=RELICS.find(function(r){return r.id==="motao"});',
'  if(!r90)errors.push("90a: motao not found");',
'  else{r90.fn(g90.player);',
'    if(!g90.player.killPulse)errors.push("90b: killPulse not set");',
'    // verify pulse pushes enemies',
'    spawnEnemy(g90,"zhikui",{});var e90=g90.enemies[0];e90.x=300;e90.y=300;e90.hp=1;',
'    spawnEnemy(g90,"zhikui",{});var e90b=g90.enemies[1];e90b.x=340;e90b.y=300;e90b.hp=50;',
'    var beforeX=e90b.x;',
'    g90.player.killPulse=true;onEnemyKilled(g90,e90,"hit");',
'    if(e90b.x===beforeX)errors.push("90c: pulse should push nearby enemy");}',
'}catch(e){errors.push("90: "+e.message)}',

'// Test 91: molian relic - formRipple flag',
'try{',
'  var g91=newGame("jian");var r91=RELICS.find(function(r){return r.id==="molian"});',
'  if(!r91)errors.push("91a: molian not found");',
'  else{r91.fn(g91.player);',
'    if(!g91.player.formRipple)errors.push("91b: formRipple not set");}',
'}catch(e){errors.push("91: "+e.message)}',

'// Test 92: moyi relic - recallDash flag',
'try{',
'  var g92=newGame("san");var r92=RELICS.find(function(r){return r.id==="moyi"});',
'  if(!r92)errors.push("92a: moyi not found");',
'  else{r92.fn(g92.player);',
'    if(!g92.player.recallDash)errors.push("92b: recallDash not set");',
'    if(!PREREQS.moyi)errors.push("92c: moyi PREREQ missing");',
'    else{var s92a={weaponType:"melee"};',
'      if(PREREQS.moyi(s92a))errors.push("92d: moyi should require dash weapon");',
'      var s92b={weaponType:"dash"};',
'      if(!PREREQS.moyi(s92b))errors.push("92e: moyi should pass with dash weapon");}}',
'}catch(e){errors.push("92: "+e.message)}',

'// Test 93: moze relic - killSpeedBurst flag',
'try{',
'  var g93=newGame("jian");var r93=RELICS.find(function(r){return r.id==="moze"});',
'  if(!r93)errors.push("93a: moze not found");',
'  else{r93.fn(g93.player);',
'    if(!g93.player.killSpeedBurst)errors.push("93b: killSpeedBurst not set");',
'    spawnEnemy(g93,"zhikui",{});var e93=g93.enemies[0];e93.hp=1;',
'    onEnemyKilled(g93,e93,"hit");',
'    if(g93.player.speedBurstT!==180)errors.push("93c: speedBurstT should be 180, got "+g93.player.speedBurstT);}',
'}catch(e){errors.push("93: "+e.message)}',

'// Test 94: moxiu relic - scentStreak flag and combo extension',
'try{',
'  var g94=newGame("jian");var r94=RELICS.find(function(r){return r.id==="moxiu"});',
'  if(!r94)errors.push("94a: moxiu not found");',
'  else{r94.fn(g94.player);',
'    if(!g94.player.scentStreak)errors.push("94b: scentStreak not set");',
'    g94.killStreakT=50;g94.player.scentStreak=true;',
'    g94.killStreakT+=15;if(g94.killStreakT>150)g94.killStreakT=150;',
'    if(g94.killStreakT!==65)errors.push("94c: killStreakT should extend to 65, got "+g94.killStreakT);}',
'}catch(e){errors.push("94: "+e.message)}',

'// Test 95: mowei relic - formDmgBonus flag',
'try{',
'  var g95=newGame("jian");var r95=RELICS.find(function(r){return r.id==="mowei"});',
'  if(!r95)errors.push("95a: mowei not found");',
'  else{r95.fn(g95.player);',
'    if(!g95.player.formDmgBonus)errors.push("95b: formDmgBonus not set");}',
'}catch(e){errors.push("95: "+e.message)}',

'// Test 96: mosui relic - critShrapnel flag',
'try{',
'  var g96=newGame("jian");var r96=RELICS.find(function(r){return r.id==="mosui"});',
'  if(!r96)errors.push("96a: mosui not found");',
'  else{r96.fn(g96.player);',
'    if(!g96.player.critShrapnel)errors.push("96b: critShrapnel not set");}',
'}catch(e){errors.push("96: "+e.message)}',

'// Test 97: moshi relic - corrosive flag',
'try{',
'  var g97=newGame("jian");var r97=RELICS.find(function(r){return r.id==="moshi"});',
'  if(!r97)errors.push("97a: moshi not found");',
'  else{r97.fn(g97.player);',
'    if(!g97.player.corrosive)errors.push("97b: corrosive not set");}',
'}catch(e){errors.push("97: "+e.message)}',

'// Test 98: monu relic - lowHpFury flag',
'try{',
'  var g98=newGame("jian");var r98=RELICS.find(function(r){return r.id==="monu"});',
'  if(!r98)errors.push("98a: monu not found");',
'  else{r98.fn(g98.player);',
'    if(!g98.player.lowHpFury)errors.push("98b: lowHpFury not set");}',
'}catch(e){errors.push("98: "+e.message)}',

'// Test 99: monu damage bonus at low HP',
'try{',
'  var g99=newGame("jian");var p99=g99.player;p99.lowHpFury=true;p99.hp=40;p99.maxHp=100;',
'  var baseDmg=g99.weapon.dmg*p99.stats.dmg;',
'  var boostedDmg=Math.floor(baseDmg*1.25);',
'  if(boostedDmg<=baseDmg)errors.push("99a: lowHpFury dmg not applying");',
'}catch(e){errors.push("99: "+e.message)}',

'// Test 100: moyong enemy type exists',
'try{',
'  if(!ETYPE.moyong)errors.push("100a: moyong not found");',
'  if(ETYPE.moyong.spawnsOnDeath!==true)errors.push("100b: moyong spawnsOnDeath wrong");',
'  if(ETYPE.moyong.spawnType!=="morui")errors.push("100c: moyong spawnType wrong");',
'  if(ETYPE.moyong.spawnCount!==2)errors.push("100d: moyong spawnCount wrong");',
'}catch(e){errors.push("100: "+e.message)}',

'// Test 101: morui enemy type exists',
'try{',
'  if(!ETYPE.morui)errors.push("101a: morui not found");',
'  if(ETYPE.morui.hp!==12)errors.push("101b: morui hp wrong");',
'  if(ETYPE.morui.spd!==3.6)errors.push("101c: morui spd wrong");',
'}catch(e){errors.push("101: "+e.message)}',

'// Test 102: PREREQS for moshi (needs molian)',
'try{',
'  var s102={ownedIds:{}};',
'  if(PREREQS.moshi(s102))errors.push("102a: moshi should require molian");',
'  s102.ownedIds.molian=true;',
'  if(!PREREQS.moshi(s102))errors.push("102b: moshi should unlock with molian");',
'}catch(e){errors.push("102: "+e.message)}',

'// Test 103: PREREQS for monu (needs tongjing)',
'try{',
'  var s103={ownedIds:{}};',
'  if(PREREQS.monu(s103))errors.push("103a: monu should require tongjing");',
'  s103.ownedIds.tongjing=true;',
'  if(!PREREQS.monu(s103))errors.push("103b: monu should unlock with tongjing");',
'}catch(e){errors.push("103: "+e.message)}',

'// Test 104: zhibao curse extraStartRelics',
'try{',
'  var g104=newGame("jian","normal");',
'  var c104=CURSES.find(function(x){return x.id==="zhibao"});',
'  if(!c104)errors.push("104a: zhibao not found");',
'  else{',
'    c104.fn(g104.player);',
'    if(g104.player.extraStartRelics!==2)errors.push("104b: extraStartRelics should be 2, got "+g104.player.extraStartRelics);',
'    if(g104.player.maxHpOverride!==60)errors.push("104c: maxHpOverride should be 60, got "+g104.player.maxHpOverride);',
'    // Simulate beginRun loop',
'    var _ec=g104.player.extraStartRelics;',
'    g104.player.extraStartRelics=0;',
'    for(var esi=0;esi<_ec;esi++){',
'      var rc=pickRelicChoices(g104);',
'      if(!rc||rc.length===0)errors.push("104d: pickRelicChoices returned empty at esi="+esi);',
'      else{var r=rc[0];g104.relics.push(r);try{r.fn(g104.player)}catch(e){errors.push("104e: fn threw "+e.message)}}',
'    }',
'    if(g104.relics.length!==2)errors.push("104f: expected 2 relics, got "+g104.relics.length);',
'    // Check relics are distinct',
'    if(g104.relics.length>=2&&g104.relics[0].id===g104.relics[1].id)errors.push("104g: duplicate relic "+g104.relics[0].id);',
'    var g104b=newGame("jian","normal");',
'    c104.fn(g104b.player);',
'    beginRun(g104b);',
'    if(g104b.relics.length!==2)errors.push("104h: beginRun should grant 2 relics, got "+g104b.relics.length);',
'    if(g104b.player.extraStartRelics!==0)errors.push("104i: extraStartRelics should be consumed, got "+g104b.player.extraStartRelics);',
'    if(g104b.player.maxHp!==60)errors.push("104j: maxHp should be 60 after beginRun, got "+g104b.player.maxHp);',
'  }',
'}catch(e){errors.push("104: "+e.message)}',

'// Test 105: critShrapnel only on crits (mosui/sui)',
'try{',
'  var msui=RELICS.find(function(r){return r.id==="mosui"});',
'  if(!msui)errors.push("105a: mosui not found");',
'  else{var g105=newGame("jian","normal");msui.fn(g105.player);',
'    if(!g105.player.critShrapnel)errors.push("105b: critShrapnel not set");',
'  }',
'}catch(e){errors.push("105: "+e.message)}',

'// Test 106: spirit damage base value (reduced from 5 to 4)',
'try{',
'  var g106=newGame("jian","normal");',
'  g106.player.hasInkSpirit=true;g106.player.inkSpiritCount=1;',
'  startWave(g106);',
'  // After wave start, spirit spawns',
'  for(var si=0;si<100;si++)update(g106);',
'  if(g106.inkSpirits.length>0){',
'    var sd=g106.inkSpirits[0].dmg;',
'    if(sd>4)errors.push("106a: spirit base dmg should be <=4, got "+sd);',
'    if(sd<3)errors.push("106b: spirit base dmg should be >=3, got "+sd);',
'  }',
'}catch(e){errors.push("106: "+e.message)}',

'// Test 107: HUD relic list is summarized after 5 relics',
'try{',
'  var hudStore={};',
'  document.getElementById=function(id){',
'    if(id==="gameCanvas")return canvas;',
'    if(!hudStore[id])hudStore[id]={style:{display:"none"},classList:{add:function(){},remove:function(){}},innerHTML:"",textContent:"",addEventListener:function(){},focus:function(){},offsetWidth:0,querySelectorAll:function(){return[]},closest:function(){return null}};',
'    return hudStore[id];',
'  };',
'  var g107=newGame("jian","normal");',
'  g107.relics=RELICS.slice(0,7);',
'  _hudCache={};_lastRelicHTML="";',
'  updateHUD(g107);',
'  if(hudStore.hudRelics.innerHTML.indexOf("+2件")<0)errors.push("107a: missing +2 summary in HUD");',
'  if((hudStore.hudRelics.innerHTML.match(/<span class="hud__relic-tag/g)||[]).length>6)errors.push("107b: too many HUD relic tags");',
'}catch(e){errors.push("107: "+e.message)}',

// === Easter egg achievement tests ===

// Test 108: Achievement count includes new easter eggs
'try{var eggIds=["no_move_win","low_hurt_win","speed_clear","paper_win","no_relic_win","massacre","perfect_boss","no_evolve_win"];',
'  eggIds.forEach(function(eid){',
'    var found=ACHIEVEMENTS.some(function(a){return a.id===eid});',
'    if(!found)errors.push("easter-achievements: missing "+eid);',
'  });',
'  if(ACHIEVEMENTS.length<26)errors.push("easter-achievements: expected >=26, got "+ACHIEVEMENTS.length);',
'}catch(e){errors.push("easter-achievements: "+e.message)}',

// Test 109: hurtCount increments on damage
'try{var g109=newGame("jian");startWave(g109);g109.announceT=0;',
'  spawnEnemy(g109,"zhikui",{noScale:true});var e=g109.enemies[g109.enemies.length-1];e.spawnGraceT=0;',
'  var hc=g109.hurtCount;hurtP(g109,10,e);',
'  if(g109.hurtCount!==hc+1)errors.push("hurtCount: expected increment, got "+g109.hurtCount);',
'}catch(e){errors.push("hurtCount: "+e.message)}',

// Test 110: usedMoveKey starts false
'try{var g110=newGame("jian");',
'  if(g110.usedMoveKey!==false)errors.push("usedMoveKey: should start false");',
'}catch(e){errors.push("usedMoveKey-init: "+e.message)}',

// Test 111: fastWaveClear detection (wave cleared in <30s)
'try{var g111=newGame("jian");g111.wave=1;startWave(g111);g111.announceT=0;',
'  g111.waveFirstKillT=100;g111.time=100+500;',
'  var allE=g111.enemies.slice();',
'  for(var i=0;i<allE.length;i++){if(allE[i].hp>0)damageEnemy(g111,allE[i],9999,"hit");}',
'  for(var i=0;i<60;i++)update(g111);',
'  if(!g111.waveCleared)errors.push("fastWaveClear: wave not cleared, enemies="+g111.enemies.length);',
'  else if(!g111.fastWaveClear)errors.push("fastWaveClear: should be true for <30s clear, firstKill="+g111.waveFirstKillT+" time="+g111.time);',
'}catch(e){errors.push("fastWaveClear: "+e.message)}',

// Test 112: bossHurtThisWave tracking
'try{var g112=newGame("jian");g112.wave=1;startWave(g112);g112.announceT=0;',
'  g112._isBossWave=true;g112.bossHurtThisWave=false;',
'  hurtP(g112,10,null);',
'  if(!g112.bossHurtThisWave)errors.push("bossHurt: should be true after hurtP during boss wave");',
'}catch(e){errors.push("bossHurt: "+e.message)}',

// Test 113: no-hurt boss wave stays false
'try{var g113=newGame("jian");g113.wave=1;startWave(g113);g113.announceT=0;',
'  g113._isBossWave=true;g113.bossHurtThisWave=false;g113.player.invTimer=200;',
'  for(var i=0;i<100;i++)update(g113);',
'  if(g113.bossHurtThisWave)errors.push("noHurtBoss: should stay false without hurtP");',
'}catch(e){errors.push("noHurtBoss: "+e.message)}',

// Test 114: metaRecordRun writes easter egg fields
'try{var g114=newGame("jian");g114.state="victory";',
'  g114.kills=120;g114.hurtCount=1;g114.usedMoveKey=false;g114.relics=[];',
'  g114._isBossWave=true;g114.bossHurtThisWave=false;g114.fastWaveClear=true;',
'  g114.player.maxHpOverride=60;g114.player.noEvolution=true;',
'  meta.noMoveWins=0;meta.lowHurtWins=0;meta.fastWaveClears=0;meta.paperWins=0;',
'  meta.noRelicWins=0;meta.bestSingleRunKills=0;meta.perfectBossKills=0;meta.noEvolveWins=0;',
'  metaRecordRun(g114);',
'  if(!meta.noMoveWins)errors.push("metaEaster: noMoveWins not set");',
'  if(!meta.lowHurtWins)errors.push("metaEaster: lowHurtWins not set");',
'  if(!meta.fastWaveClears)errors.push("metaEaster: fastWaveClears not set");',
'  if(!meta.paperWins)errors.push("metaEaster: paperWins not set");',
'  if(!meta.noRelicWins)errors.push("metaEaster: noRelicWins not set");',
'  if(meta.bestSingleRunKills!==120)errors.push("metaEaster: bestSingleRunKills expected 120 got "+meta.bestSingleRunKills);',
'  if(!meta.perfectBossKills)errors.push("metaEaster: perfectBossKills not set");',
'  if(!meta.noEvolveWins)errors.push("metaEaster: noEvolveWins not set");',
'}catch(e){errors.push("metaEaster: "+e.message)}',

// Test 115: Achievement unlock returns newly unlocked array
'try{',
'  var meta115=loadMeta();meta115.achievements={};meta115.totalRuns=1;meta115.bestGrade="";',
'  meta115.totalKills=100;meta115.bestWave=0;meta115.weaponsCleared={};',
'  meta115.relicsDiscovered={};meta115.cursesUsed={};meta115.bossKills=0;meta115.mojiangjunKills=0;',
'  meta115.nightmareWins=0;meta115.eliteKills=0;meta115.bestFireKills=0;meta115.unlocks={};',
'  var ach=checkAchievements(meta115);',
'  if(!ach||!ach.length)errors.push("115a: checkAchievements should return array for first_run");',
'  var hasFirst=ach.some(function(a){return a.id==="first_run"});',
'  if(!hasFirst)errors.push("115b: first_run should be in newly unlocked");',
'  if(!meta115.achievements.first_run)errors.push("115c: first_run should be saved to meta");',
'}catch(e){errors.push("115: "+e.message)}',

// Test 116: DeathCause shows proper names for hazards
'try{',
'  var g116=newGame("jian");startWave(g116);',
'  g116.player.invTimer=0;g116.player.hp=1;g116.player.maxHp=100;',
'  hurtP(g116,5,{name:"墨雨"});',
'  if(g116.deathCause!=="墨雨")errors.push("116: deathCause should be 墨雨, got "+g116.deathCause);',
'}catch(e){errors.push("116: "+e.message)}',

// Test 117: perfMul cache in game state
'try{',
'  var g117=newGame("jian");startWave(g117);',
'  g117.particles=new Array(200);for(var pi=0;pi<200;pi++)g117.particles[pi]={life:1,maxLife:1};',
'  update(g117);',
'  if(g117._pm==null)errors.push("117a: g._pm should be set after update");',
'  if(typeof g117._pm!=="number")errors.push("117b: g._pm should be a number");',
'}catch(e){errors.push("117: "+e.message)}',

// Test 118: Third evolution — 4 new evolutions exist in EVOLUTIONS
'try{',
'  var evoIds=["e_huizhan","e_suopo","e_huiming","e_yingji"];',
'  var evoKeys=["melee","ranged","aoe","dash"];',
'  for(var ei=0;ei<evoIds.length;ei++){',
'    var pool=EVOLUTIONS[evoKeys[ei]]||[];',
'    var found=pool.some(function(e){return e.id===evoIds[ei]});',
'    if(!found)errors.push("118a: evolution "+evoIds[ei]+" missing from "+evoKeys[ei]);',
'    var match=pool.filter(function(e){return e.id===evoIds[ei]})[0];',
'    if(match&&typeof match.fn!=="function")errors.push("118b: "+evoIds[ei]+" fn is not a function");',
'  }',
'}catch(e){errors.push("118: "+e.message)}',

// Test 119: Ghost market stage mod exists
'try{',
'  if(!STAGE_MODS.guishi)errors.push("119a: guishi stage mod missing");',
'  else if(!STAGE_MODS.guishi.name||!STAGE_MODS.guishi.desc)errors.push("119b: guishi incomplete");',
'}catch(e){errors.push("119: "+e.message)}',

// Test 120: New ink spirit relics (baomo/yumo/hanmo/fenmo)
'try{',
'  var spRelics=["baomo","yumo","hanmo","fenmo"];',
'  spRelics.forEach(function(rid){',
'    var r=RELICS.filter(function(x){return x.id===rid})[0];',
'    if(!r)errors.push("120a: relic "+rid+" missing");',
'    else if(!r.name||!r.type||typeof r.fn!=="function")errors.push("120b: "+rid+" incomplete");',
'  });',
'}catch(e){errors.push("120: "+e.message)}',

// Test 121: New hazards (yinbing/zhijian) data valid
'try{',
'  var hIds=["yinbing","zhijian"];',
'  hIds.forEach(function(hid){',
'    var h=STAGE_HAZARDS.filter(function(x){return x.id===hid})[0];',
'    if(!h)errors.push("121a: hazard "+hid+" missing");',
'    else if(!h.name||!h.desc||!h.interval||h.interval<30)errors.push("121b: "+hid+" incomplete or interval too short");',
'  });',
'}catch(e){errors.push("121: "+e.message)}',

// Test 122: PREREQS for new relics exist
'try{',
'  if(!PREREQS)errors.push("122a: PREREQS missing");',
'  else{',
'    var prRelics=["baomo","yumo","hanmo","fenmo"];',
'    var prCount=0;',
'    prRelics.forEach(function(rid){if(typeof PREREQS[rid]==="function")prCount++});',
'    if(prCount<3)errors.push("122b: expected at least 3 PREREQS for new relics, got "+prCount);',
'  }',
'}catch(e){errors.push("122: "+e.message)}',

// Test 123: evolution3 field in newGame starts null
'try{',
'  var g123=newGame("jian");',
'  if(g123.evolution3!==null)errors.push("123a: evolution3 should start null");',
'  if(g123.evolution!==null||g123.evolution2!==null)errors.push("123b: evolution/evolution2 should start null");',
'}catch(e){errors.push("123: "+e.message)}',

// Test 124: findNearestEnemy function exists and returns correct shape
'try{',
'  var g124=newGame("jian");startWave(g124);',
'  if(typeof findNearestEnemy!=="function")errors.push("124a: findNearestEnemy not a function");',
'  var nr=findNearestEnemy(g124,480,320);',
'  if(!nr||nr.enemy===undefined||nr.distSq===undefined)errors.push("124b: findNearestEnemy should return {enemy,distSq}");',
'}catch(e){errors.push("124: "+e.message)}',

// Test 125: rebuildPlayerStats restores correct stats after relic removal
'try{',
'  var g125=newGame("jian");startWave(g125);var p125=g125.player;',
'  var baseDmg=p125.stats.dmg;',
'  var r1=RELICS.filter(function(x){return x.id==="zhusha"})[0];',
'  if(r1){g125.relics.push(r1);r1.fn(p125);',
'    var boostedDmg=p125.stats.critDmg;',
'    if(boostedDmg<=baseDmg)errors.push("125a: zhusha should boost critDmg");',
'    g125.relics.splice(g125.relics.indexOf(r1),1);',
'    rebuildPlayerStats(g125);',
'    if(g125.player.stats.critDmg>=boostedDmg)errors.push("125b: rebuildPlayerStats should remove old relic effect");',
'    if(g125.player.x!==p125.x||g125.player.y!==p125.y)errors.push("125c: rebuildPlayerStats should preserve position");',
'  }',
'}catch(e){errors.push("125: "+e.message)}',

// Test 126: collectBuffs returns array and picks up common buffs
'try{',
'  var g126=newGame("jian");startWave(g126);',
'  if(typeof collectBuffs!=="function")errors.push("126a: collectBuffs not found");',
'  else{',
'    var b0=collectBuffs(g126);',
'    if(!Array.isArray(b0))errors.push("126b: collectBuffs should return array");',
'    g126.player.fireOnKill=true;',
'    var b1=collectBuffs(g126);',
'    if(!b1.some(function(b){return b.ch==="火"}))errors.push("126c: should detect fireOnKill buff");',
'    g126.player.killSpdTimer=100;',
'    var b2=collectBuffs(g126);',
'    if(!b2.some(function(b){return b.cat==="temp"}))errors.push("126d: should detect temp buff");',
'  }',
'}catch(e){errors.push("126: "+e.message)}',

// Test 127: BUFF_DEFS has entries for key buffs
'try{',
'  if(typeof BUFF_DEFS==="undefined")errors.push("127a: BUFF_DEFS not found");',
'  else{',
'    var required=["fireOnKill","soulChain","frostOnCrit","hasInkSpirit"];',
'    required.forEach(function(k){if(!BUFF_DEFS[k])errors.push("127b: "+k+" missing from BUFF_DEFS")});',
'    Object.keys(BUFF_DEFS).forEach(function(k){',
'      var d=BUFF_DEFS[k];',
'      if(!d.label||!d.cat||!d.ch)errors.push("127c: "+k+" incomplete");',
'    });',
'  }',
'}catch(e){errors.push("127: "+e.message)}',

// Test 128: merchant trade sound exists in sound.js
'try{',
'  if(typeof sounds!=="undefined"&&typeof sounds.merchantTrade==="function"){',
'  }else if(typeof sounds==="undefined"){',
'    // sound.js not loaded in test env, skip',
'  }else{errors.push("128: sounds.merchantTrade should be a function")}',
'}catch(e){errors.push("128: "+e.message)}',

// Test 129: merchant swap with 0 relics does NOT set merchant.used
'try{',
'  var g129=newGame("jian",[]);',
'  g129.relics=[];',
'  g129.merchant={used:false};',
'  g129.relicPool=RELICS.slice(0,5);',
'  g129.player=g129.player||mkPlayer("jian");',
'  // Simulate merchant swap with 0 relics',
'  if(g129.relics.length===0){',
'    var wouldWaste=g129.merchant.used;',
'    if(wouldWaste)errors.push("129: merchant should not be consumed when 0 relics");',
'  }',
'  if(typeof g129.merchant.used!=="boolean")errors.push("129: merchant.used should be boolean");',
'}catch(e){errors.push("129: "+e.message)}',

// Test 130: merchant HP path with insufficient HP should not consume merchant
'try{',
'  var g130=newGame("jian",[]);',
'  g130.relics=[RELICS[0]];',
'  g130.merchant={used:false};',
'  g130.relicPool=RELICS.slice(0,5);',
'  g130.player=g130.player||mkPlayer("jian");',
'  g130.player.hp=10;',
'  g130.player.maxHp=100;',
'  // HP <= 30 should fail',
'  if(g130.player.hp<=30){',
'    // merchant should NOT be consumed',
'    var preUsed=g130.merchant.used;',
'    if(preUsed)errors.push("130: merchant should not be consumed when HP insufficient");',
'  }',
'}catch(e){errors.push("130: "+e.message)}',

// Test 131: merchant relic pool should filter owned relics (no duplicates)
'try{',
'  var g131=newGame("jian",[]);',
'  g131.relics=[RELICS[0],RELICS[1],RELICS[2]];',
'  // Build pool that includes owned relics',
'  g131.relicPool=[RELICS[0],RELICS[1],RELICS[3],RELICS[4]];',
'  var ownedIds={};g131.relics.forEach(function(r){ownedIds[r.id]=1});',
'  var filtered=g131.relicPool.filter(function(r){return!ownedIds[r.id]});',
'  if(filtered.length!==2)errors.push("131a: should filter to 2 non-owned, got "+filtered.length);',
'  if(filtered[0].id===RELICS[0].id||filtered[0].id===RELICS[1].id)errors.push("131b: owned relic leaked into filtered pool");',
'}catch(e){errors.push("131: "+e.message)}',

// Test 132: showRelic guard returns safely when DOM missing (does not crash state machine)
'try{',
'  var g132=newGame("jian",[]);',
'  g132.state="waveClear";',
'  g132.wave=2;',
'  // Simulate: DOM elements missing => guard triggers',
'  var el=null,sealEl=null,popupEl=null;',
'  if(!el||!sealEl||!popupEl){',
'    g132.state="playing";',
'    if(typeof startWave==="function")startWave(g132);',
'  }',
'  if(g132.state!=="playing")errors.push("132a: state should be playing after guard, got "+g132.state);',
'  if(g132.wave!==2)errors.push("132b: wave should still be 2 (not double-incremented)");',
'}catch(e){errors.push("132: "+e.message)}',

// Test 133: rebuildPlayerStats preserves kiteKills and _killBoost
'try{',
'  var g133=newGame("jian",[]);',
'  var p=g133.player||mkPlayer("jian");',
'  p.kiteKills=5;',
'  p._killBoost=true;',
'  p.x=W/2;p.y=H/2;',
'  var pos=p.x;',
'  var rk=["x","y","hp","maxHp","dodgeCd","invT","atkT","combo","dodgeUses","_tutorialStep",',
'    "slowT","execCritT","speedBurstT","atkFormCount","kiteKills","_killBoost"];',
'  var ck=["_usedMove","usedMoveKey","inkSpiritCount","noEvolution","_fragileInit"];',
'  var fresh=mkPlayer("jian");',
'  rk.forEach(function(k){if(p.hasOwnProperty(k)||k in p)fresh[k]=p[k]});',
'  ck.forEach(function(k){if(k in p)fresh[k]=p[k]});',
'  if(fresh.kiteKills!==5)errors.push("133a: kiteKills should be 5, got "+fresh.kiteKills);',
'  if(fresh._killBoost!==true)errors.push("133b: _killBoost should be true, got "+fresh._killBoost);',
'  if(fresh.x!==pos)errors.push("133c: position should be preserved");',
'}catch(e){errors.push("133: "+e.message)}',
// Test 134: ash_road achievement check (fire coverage)
'try{',
'  var m134={bestFireCoverage:0.4};',
'  var ach134=ACHIEVEMENTS.find(function(a){return a.id==="ash_road"});',
'  if(!ach134)errors.push("134a: ash_road not found in ACHIEVEMENTS");',
'  if(ach134&&ach134.check(m134))errors.push("134b: 40% coverage should NOT unlock");',
'  m134.bestFireCoverage=0.55;',
'  if(ach134&&!ach134.check(m134))errors.push("134c: 55% coverage SHOULD unlock");',
'  if(ach134&&ach134.reward!=="goldInk")errors.push("134d: reward should be goldInk");',
'}catch(e){errors.push("134: "+e.message)}',

// Test 135: all_weapons achievement check
'try{',
'  var m135={weaponsCleared:{jian:1,bi:1,ling:1}};',
'  var ach135=ACHIEVEMENTS.find(function(a){return a.id==="all_weapons"});',
'  if(!ach135)errors.push("135a: all_weapons not found in ACHIEVEMENTS");',
'  if(ach135&&ach135.check(m135))errors.push("135b: 3 weapons should NOT unlock");',
'  m135.weaponsCleared.san=1;',
'  if(ach135&&!ach135.check(m135))errors.push("135c: 4 weapons SHOULD unlock");',
'  var m135b={weaponsCleared:{}};',
'  if(ach135&&ach135.check(m135b))errors.push("135d: 0 weapons should NOT unlock");',
'}catch(e){errors.push("135: "+e.message)}',
// Test 136: spawnPulse is set on elite and boss enemies
'try{',
'  var g136=newGame("jian");startWave(g136);',
'  spawnEnemy(g136,"zhikui",{noScale:true});',
'  var normal=g136.enemies[g136.enemies.length-1];',
'  if(normal.spawnPulse!==0)errors.push("136a: normal enemy should have spawnPulse=0, got "+normal.spawnPulse);',
'  spawnEnemy(g136,"shigui",{noScale:true,midBoss:true});',
'  var midBoss=g136.enemies[g136.enemies.length-1];',
'  if(midBoss.spawnPulse!==16)errors.push("136b: midBoss should have spawnPulse=16, got "+midBoss.spawnPulse);',
'  // Boss enemy',
'  var bossT=ETYPE.mojiangjun||ETYPE.zhikui;',
'  if(bossT&&bossT.isBoss){',
'    spawnEnemy(g136,"mojiangjun",{noScale:true});',
'    var boss=g136.enemies[g136.enemies.length-1];',
'    if(boss.spawnPulse!==16)errors.push("136c: boss should have spawnPulse=16, got "+boss.spawnPulse);',
'  }',
'}catch(e){errors.push("136: "+e.message)}',
// Test 137: new curse moqi exists and applies correctly
'try{',
'  var c137=CURSES.find(function(x){return x.id==="moqi"});',
'  if(!c137)errors.push("137a: moqi curse not found");',
'  else{',
'    var p137=mkPlayer("jian");c137.fn(p137);',
'    if(!p137.critHeal)errors.push("137b: critHeal flag not set");',
'    if(p137.stats.range>=1)errors.push("137c: range should be reduced, got "+p137.stats.range);',
'  }',
'}catch(e){errors.push("137: "+e.message)}',

// Test 138: new stage mod mirror exists and stageOnEnemyKilled spawns ghost projectile
'try{',
'  var sm138=STAGE_MODS.mirror;',
'  if(!sm138)errors.push("138a: mirror stage mod not found");',
'  else if(!sm138.name)errors.push("138b: mirror has no name");',
'  var g138=newGame("jian");startWave(g138);g138.stage={id:"mirror"};',
'  spawnEnemy(g138,"zhikui",{noScale:true});',
'  var e138=g138.enemies[g138.enemies.length-1];',
'  var eBefore=g138.eProj.length;',
'  if(e138)stageOnEnemyKilled(g138,e138);',
'  if(g138.eProj.length<=eBefore)errors.push("138c: mirror should spawn ghost proj on kill, got "+g138.eProj.length+"/"+eBefore);',
'}catch(e){errors.push("138: "+e.message)}',
// Test 139: new curse kuangmo exists and has correct effects
'try{',
'  var c139=CURSES.find(function(x){return x.id==="kuangmo"});',
'  if(!c139)errors.push("139a: kuangmo curse not found");',
'  else{',
'    var p139=mkPlayer("jian");c139.fn(p139);',
'    if(!p139.atkHpCost)errors.push("139b: atkHpCost flag not set");if(!p139.killHeal||p139.killHeal<8)errors.push("139b2: killHeal should be >= 8, got "+(p139.killHeal||0));',
'    if(p139.stats.atkSpd>=0.85)errors.push("139c: atkSpd should be reduced, got "+p139.stats.atkSpd);',
'  }',
'}catch(e){errors.push("139: "+e.message)}',
// Test 140: zhibao curse gives 2 extra starting relics via beginRun
'try{',
'  var g140=newGame("jian","normal");',
'  var curse140=CURSES.find(function(c){return c.id==="zhibao"});',
'  if(!curse140)errors.push("140a: zhibao curse not found");',
'  else{',
'    var p140=g140.player;',
'    curse140.fn(p140);',
'    if(p140.extraStartRelics!==2)errors.push("140b: extraStartRelics should be 2, got "+p140.extraStartRelics);',
'    if(p140.maxHpOverride!==60)errors.push("140c: maxHpOverride should be 60, got "+p140.maxHpOverride);',
'    // Simulate beginRun: pick extra relics',
'    p140.extraStartRelics=0;',
'    if(p140.maxHpOverride>0){p140.maxHp=p140.maxHpOverride;p140.hp=Math.min(p140.hp,p140.maxHp)}',
'    for(var esi=0;esi<2;esi++){',
'      try{var rc=pickRelicChoices(g140)}catch(e2){rc=[]}',
'      if(rc&&rc.length>0){',
'        var r=rc[0];g140.relics.push(r);',
'        try{r.fn(p140)}catch(e3){}',
'      }else{errors.push("140d"+esi+": pickRelicChoices returned empty for extra relic "+esi)}',
'    }',
'    if(g140.relics.length<2)errors.push("140e: should have at least 2 relics, got "+g140.relics.length);',
'    if(p140.maxHp!==60)errors.push("140f: maxHp should be 60 after beginRun, got "+p140.maxHp);',
'  }',
'}catch(e){errors.push("140: "+e.message)}',
// Test 141: rebuildPlayerStats preserves relicPower bonuses after merchant swap
'try{',
'  var g141=newGame("jian","normal");',
'  var p141=g141.player;',
'  var shihun141=CURSES.find(function(c){return c.id==="shihun"});',
'  if(!shihun141)errors.push("141a: shihun curse not found");',
'  else{',
'    shihun141.fn(p141);',
'    if(p141.relicPower!==1.8)errors.push("141b: relicPower should be 1.8");',
'    if(!p141._relicPowerApplied){',
'      p141.stats.dmg+=(p141.relicPower-1)*0.12;',
'      p141.stats.critDmg+=(p141.relicPower-1)*0.2;',
'      p141._relicPowerApplied=true;',
'    }',
'    var dmgBefore=p141.stats.dmg;',
'    var critBefore=p141.stats.critDmg;',
'    rebuildPlayerStats(g141);',
'    var p141b=g141.player;',
'    if(Math.abs(p141b.stats.dmg-dmgBefore)>0.001)errors.push("141c: dmg lost on rebuild: "+dmgBefore+"->"+p141b.stats.dmg);',
'    if(Math.abs(p141b.stats.critDmg-critBefore)>0.001)errors.push("141d: critDmg lost on rebuild: "+critBefore+"->"+p141b.stats.critDmg);',
'  }',
'}catch(e){errors.push("141: "+e.message)}',

// Test 142: v2.21 RANGES + TUNING new constants + forEachLiveEnemy
'try{',
'  var newRanges=["killPulse","critShrapnel","dodgeSoulGrab","inkSpirit","spiritExplode","swoop","mimicReveal","buffAura"];',
'  for(var ri2=0;ri2<newRanges.length;ri2++){',
'    if(typeof RANGES[newRanges[ri2]]!=="number")errors.push("142a: RANGES."+newRanges[ri2]+" missing");',
'  }',
'  var newTuning=["killStreakWindow","speedBurstDuration","spawnGraceDuration","deathAnimDuration","buffedSpdMult","defaultSlowAmount","fireTickInterval","survivalMaxEnemies","survivalSpawnBase","survivalSpawnJitter"];',
'  for(var ti=0;ti<newTuning.length;ti++){',
'    if(typeof TUNING[newTuning[ti]]!=="number")errors.push("142b: TUNING."+newTuning[ti]+" missing");',
'  }',
'  if(TUNING.killStreakWindow!==120)errors.push("142c: killStreakWindow should be 120, got "+TUNING.killStreakWindow);',
'  if(TUNING.spawnGraceDuration!==30)errors.push("142d: spawnGraceDuration should be 30");',
'  if(TUNING.buffedSpdMult!==1.3)errors.push("142e: buffedSpdMult should be 1.3");',
'  if(RANGES.killPulse!==100)errors.push("142f: killPulse range should be 100");',
'  if(RANGES.inkSpirit!==220)errors.push("142g: inkSpirit range should be 220");',
'  // forEachLiveEnemy: verify no raw g.enemies.forEach with hp/grace guard remains in combat code',
'  var feSrc=fs.readFileSync("game.js","utf8");',
'  var suspectPatterns=feSrc.match(/g\\.enemies\\.forEach\\(function\\([a-z]+\\)\\{if\\([a-z]+\\.hp<=0\\|\\|[a-z]+\\.spawnGraceT>0\\)return/g);',
'  if(suspectPatterns&&suspectPatterns.length>0)errors.push("142h: "+suspectPatterns.length+" raw enemy forEach with hp/grace guard remain: "+suspectPatterns[0].substring(0,60));',
'  // filter().length in hot path should be gone',
'  var filterLen=feSrc.match(/g\\.enemies\\.filter\\(function\\(e\\)\\{return e\\.isBoss&&e\\.hp>0\\}\\)\\.length/g);',
'  if(filterLen)errors.push("142i: filter().length still present in survival boss check");',
'}catch(e){errors.push("142: "+e.message)}',

// Test 143: v2.22 performance + bug fixes
'try{',
'  // Kill milestones hoisted as module constant',
'  if(typeof KILL_MILESTONES==="undefined")errors.push("143a: KILL_MILESTONES not defined");',
'  else if(KILL_MILESTONES.length!==5)errors.push("143b: KILL_MILESTONES should have 5 entries");',
'  else if(KILL_MILESTONES[0].at!==3||KILL_MILESTONES[4].at!==30)errors.push("143c: KILL_MILESTONES values wrong");',
'  // New TUNING constants',
'  var v22t=["killSpeedBonus","speedBurstBonus","lowHpFuryBonus","lowHpFuryThreshold","eliteHpMult","eliteSpdMult","eliteArmoredSpdMult","reviveInvFrames"];',
'  for(var ti3=0;ti3<v22t.length;ti3++){if(typeof TUNING[v22t[ti3]]!=="number")errors.push("143d: TUNING."+v22t[ti3]+" missing")}',
'  if(TUNING.killSpeedBonus!==0.25)errors.push("143e: killSpeedBonus wrong");',
'  if(TUNING.eliteHpMult!==1.5)errors.push("143f: eliteHpMult wrong");',
'  if(TUNING.reviveInvFrames!==60)errors.push("143g: reviveInvFrames wrong");',
'  // No inline milestone array recreation in onEnemyKilled',
'  var gm2=fs.readFileSync("game.js","utf8");',
'  if(gm2.indexOf("var ks=g.killStreak,km=[{at:3")!==-1)errors.push("143h: inline kill milestones not hoisted");',
'  // deathburst maxTimer fix',
'  if(gm2.indexOf("timer:30,r:50}")!==-1)errors.push("143i: elite deathburst missing maxTimer");',
'  // leeches.filter replaced with in-place loop',
'  if(gm2.indexOf("leeches.filter")!==-1)errors.push("143j: leeches.filter not replaced");',
'  // dstSq(p,{x:db.x,y:db.y}) simplified to dstSq(p,db)',
'  if(gm2.indexOf("dstSq(p,{x:db.x")!==-1)errors.push("143k: redundant object in dstSq not removed");',
'}catch(e){errors.push("143: "+e.message)}',

// Test 144: PREREQS fengmofu filtering (v3.0)
'try{',
'  var g146=newGame("jian");',
'  var _s146=buildPickState(g146);',
'  if(PREREQS.fengmofu(_s146))errors.push("146a: fengmofu should be blocked without slow");',
'  g146.player.slowOnHit=0.4;',
'  var _s146b=buildPickState(g146);',
'  if(!PREREQS.fengmofu(_s146b))errors.push("146b: fengmofu should pass with slow");',
'}catch(e){errors.push("146: "+e.message)}',

// Test 147: rebuildPlayerStats preserves recallMark + justDodged (v3.0)
'try{',
'  var g147=newGame("jian");',
'  g147.player.recallMark={x:100,y:200,life:30,maxLife:30};',
'  g147.player.justDodged=true;',
'  g147.relics.push(RELICS[0]);',
'  rebuildPlayerStats(g147);',
'  if(!g147.player.recallMark)errors.push("147a: recallMark lost");',
'  if(g147.player.recallMark.x!==100)errors.push("147b: recallMark corrupted");',
'  if(!g147.player.justDodged)errors.push("147c: justDodged lost");',
'}catch(e){errors.push("147: "+e.message)}',

// Test 148: PREREQS count = 30 (v3.0)
'try{',
'  var _pc148=Object.keys(PREREQS).length;',
'  if(_pc148!==30)errors.push("148a: PREREQS count="+_pc148+" expected 30");',
'}catch(e){errors.push("148: "+e.message)}',

'if(errors.length){console.log("FAIL ("+errors.length+"):");errors.forEach(function(e){console.log("  - "+e)});process.exit(1)}',
'else{console.log("ALL 108 TESTS PASSED");',
'  console.log(" 37-62. (previous 26 tests)");',
'  console.log(" 63-68. v2.10 (墨阵/墨童/阵眼/墨竭)");',
'  console.log(" 69-78. v2.11 (墨镜/回春阵/墨涡/墨蝠/墨瘴/墨吸/墨甲)");',
'  console.log(" 79-85. v2.12 (墨爆/墨弦/墨蝶)");',
'  console.log(" 86-95. v2.13 (墨钉/墨澄/墨涛/墨涟/墨移/墨泽/墨嗅/墨威)");',
'  console.log(" 96-106. v2.14 (墨碎/墨蚀/墨怒/墨蛹/墨蚋)");',
'  console.log(" 107. v2.14.2 (HUD遗物汇总)");',
'  console.log(" 108-114. v2.15 (彩蛋成就)");',
'  console.log(" 115-117. v2.16 (成就显示/死因名称/perfMul缓存)");',
'  console.log(" 118-125. v2.17 (第三进化/鬼市/墨灵遗物/新环境事件/遗物交换)");',
'  console.log(" 126-133. v2.17 审计修复 (商人边界/showRelic守卫/遗物重建/音效)");',
'  console.log(" 134-135. v2.17 新成就 (灰烬之路/全法器皆通)");',
'  console.log(" 136. v2.17 视觉增强 (精英出场脉冲/环境墨点)");',
'  console.log(" 137-138. v2.18 新内容 (墨契诅咒/镜殿关卡)");',
'  console.log(" 139. v2.18 狂墨诅咒/音效补充 (精英脉冲/残影弹/暴击回血/重开)");',
'  console.log(" 140. 纸薄诅咒开局遗物回归测试");',
'  console.log(" 141. v2.20 审计修复 (rebuild字段/aliveCount/tooltip/灵敏度)");',
'  console.log(" 142. v2.21 代码质量 (RANGES/TUNING常量/forEachLiveEnemy/filter→some)");',
'  console.log(" 143. v2.22 性能修复 (kill里程碑常量/decoy内联/deathburst修复/leeches优化)");',
'  console.log(" 144. v3.0 PREREQS fengmofu过滤验证");',
'  console.log(" 145. v3.0 rebuildPlayerStats保留recallMark");',
'  console.log(" 146. v3.0 PREREQS计数=30");',
'}',
].join('\n');

eval(code);
