var W=960,H=640,A={l:28,t:28,r:W-28,b:H-28};
var WAVE_SCALE={hpPerWave:0.065,spdPerWave:0.012};
var C={paper:"#f1e6d4",edge:"#d9c9af",ink:"#171310",soft:"#2c2520",
  accent:"#a33a2d",ash:"#8d7d69",moss:"#4d6156",
  ghost:"rgba(220,210,190,0.7)",ghostE:"rgba(23,19,16,0.35)",
  fire:"#c45a2d",fireG:"rgba(196,90,45,0.3)",
  spirit:"rgba(90,140,100,0.55)",spiritG:"rgba(77,122,86,0.25)",
  boss:"#6b3a5c",bossG:"rgba(107,58,92,0.3)",
  gold:"#9c835a",goldG:"rgba(156,131,90,0.24)",
  frost:"#b8c8d4",frostE:"#7fa0b4",
  ivory:"#f7efe5",clear:"rgba(0,0,0,0)",
  fontBody:'"STKaiti","KaiTi","Noto Sans SC","Droid Sans Fallback",sans-serif',
  fontTitle:'"STKaiti","KaiTi","Noto Sans SC","Droid Sans Fallback",sans-serif,serif'};

var WEAPONS=[
  {id:"jian",name:"斩妖剑",tone:"近战 / 破绽 / 处决",blurb:"三段贴身剑势，第三击挑出破绽。",
   tags:["近战","处决","暴击"],dmg:20,range:60,arc:Math.PI*0.55,cd:16,type:"melee"},
  {id:"bi",name:"符骨笔",tone:"远程 / 法术 / 魂伤",blurb:"用骨笔挥出半月墨痕，拖出魂丝。",
   tags:["远程","法术","魂"],dmg:16,range:420,arc:0,cd:18,type:"ranged",spd:7},
  {id:"ling",name:"镇魂铃",tone:"控场 / 召物 / 魂域",blurb:"铃响就是领域，怪被拉进你的节拍。",
   tags:["控场","魂","召物"],dmg:16,range:100,arc:Math.PI*2,cd:28,type:"aoe"},
  {id:"san",name:"伏魔伞",tone:"闪避 / 远程 / 反击",blurb:"撑伞吞压力，折返反击夺回节奏。",
   tags:["闪避","远程","反击"],dmg:18,range:140,arc:0,cd:26,type:"dash"},
  {id:"fan",name:"召魂幡",tone:"召唤 / 法术 / 魂伤",blurb:"竖幡招魂，幽魂自寻敌。",
   tags:["召物","法术","魂"],dmg:10,range:200,arc:0,cd:40,type:"summon",spd:0}
];

var RELICS=[
  {id:"zhusha",name:"朱砂封钉",type:"凶器",tags:["处决","暴击"],effect:"暴击伤害+40%",fn:function(p){p.stats.critDmg+=0.4}},
  {id:"kuhao",name:"枯毫遗墨",type:"残器",tags:["近战","魂"],effect:"每3次攻击释放墨刃",fn:function(p){p.tripleBlade=true}},
  {id:"zhiren",name:"纸人替魄",type:"法具",tags:["闪避","生存"],effect:"受伤时替身吸收伤害",fn:function(p){p.decoyHP=45}},
  {id:"chenfu",name:"无字谶符",type:"符物",tags:["法术","魂"],effect:"攻击附带8点魂伤，每遗物+1",fn:function(p){p.soulDmg+=8;p.soulDmgPerRelic=true}},
  {id:"lingshe",name:"青铜镇铃舌",type:"古铃",tags:["控场","召物"],effect:"攻击范围+25%",fn:function(p){p.stats.range+=0.25}},
  {id:"jingjuan",name:"倒写经卷",type:"残卷",tags:["远程","分裂"],effect:"攻击追加折返墨迹",fn:function(p){p.bounce=true;p.stats.returnInk+=1}},
  {id:"yedeng",name:"夜灯残烬",type:"烛具",tags:["火","击杀"],effect:"击杀留下磷火",fn:function(p){p.fireOnKill=true}},
  {id:"xianghui",name:"祟面香灰",type:"禁物",tags:["诅咒","暴击"],effect:"低血量时伤害+50%",fn:function(p){p.lowHpDmg+=0.5}},
  {id:"xuanbing",name:"玄冰简穗",type:"祠器",tags:["控场","冰"],effect:"攻击减速敌人",fn:function(p){p.slowOnHit=0.4}},
  {id:"xuezhu",name:"血烛祭片",type:"禁物",tags:["诅咒","火"],effect:"范围+25%，但受伤+10%",fn:function(p){p.stats.range+=0.25;p.extraDmgTaken=(p.extraDmgTaken||0)+0.1}},
  {id:"dieyin",name:"鬼脊蝶印",type:"异印",tags:["魂","远程"],effect:"魂伤跳印附近敌人",fn:function(p){p.soulChain=true}},
  {id:"pojing",name:"破镜残片",type:"镜片",tags:["闪避","反击"],effect:"闪避后攻击穿透",fn:function(p){p.pierceOnDodge=true}},
  {id:"zhijia",name:"纸甲残片",type:"护具",tags:["生存","近战"],
    effect:"受到伤害减少20%",fn:function(p){p.stats.def+=0.2}},
  {id:"zouma",name:"走马灯片",type:"灯器",tags:["机动","击杀"],
    effect:"移速+15%，击杀短暂加速",fn:function(p){p.stats.spd+=0.15;p.killSpeed=true}},
  {id:"mochi",name:"墨池残砚",type:"文房",tags:["法术","近战"],
    effect:"连续命中同一目标伤害递增",fn:function(p){p.comboDmg=true}},
  {id:"zhenmu",name:"镇墓兽首",type:"镇物",tags:["反击","生存"],
    effect:"受击时反弹50%伤害",fn:function(p){p.thorns=(p.thorns||0)+0.5}},
  {id:"yindeng",name:"引魂灯笼",type:"灯器",tags:["魂","生存"],
    effect:"击杀敌人回复5点生命",fn:function(p){p.killHeal=(p.killHeal||0)+5}},
  {id:"huangquan",name:"黄泉引路",type:"路标",tags:["火","机动"],
    effect:"移动路径留下减速墨迹",fn:function(p){p.inkTrail=true}},
  {id:"nuomian",name:"傩面碎片",type:"傩物",tags:["控场","暴击"],
    effect:"暴击时恐惧周围敌人",fn:function(p){p.fearOnCrit=true}},
  {id:"molang",name:"墨龙珠",type:"珠玉",tags:["魂","远程"],
    effect:"停顿蓄势后下一击+80%伤害",fn:function(p){p.chargeDmg=0.8}},
  {id:"tongjing",name:"铜镜照妖",type:"镜器",tags:["处决","暴击"],
    effect:"暴击时暴露敌人弱点，后续伤害+25%",fn:function(p){p.weakpointDmg=(p.weakpointDmg||0)+0.25}},
  {id:"zhaohun",name:"招魂残幡",type:"幡器",tags:["生存","召物"],
    effect:"死亡一次后以30%生命复活",fn:function(p){p.revive=true}},
  {id:"gudi",name:"骨笛残声",type:"笛器",tags:["魂","击杀"],
    effect:"击杀后攻击速度大幅提升3秒",fn:function(p){p.killAtkSpd=true}},
  {id:"xuemo",name:"血墨混染",type:"禁物",tags:["诅咒","近战"],
    effect:"低血时攻击范围+40%，但受伤+25%",fn:function(p){p.lowHpRange=true;p.extraDmgTaken=(p.extraDmgTaken||0)+0.25}},
  {id:"panwen",name:"判官断文",type:"判文",tags:["处决","暴击"],
    effect:"暴击击杀短暂提升暴击率",fn:function(p){p.execCritBonus=true}},
  {id:"zhupi",name:"朱批残页",type:"判文",tags:["处决","魂"],
    effect:"击杀带弱点的敌人时附近敌人获得弱点",fn:function(p){p.weakSpread=true}},
  {id:"xueqi",name:"血契剑穗",type:"剑具",tags:["近战","处决"],
    effect:"近战击杀返还攻击冷却",fn:function(p){p.meleeCdRefund=true}},
  {id:"liuying",name:"留影伞骨",type:"伞具",tags:["闪避","反击"],
    effect:"闪避后原地留残影吸引敌人",fn:function(p){p.decoyOnDodge=true}},
  {id:"huosui",name:"火祟牙",type:"火具",tags:["火","击杀"],
    effect:"磷火击杀扩大火场半径",fn:function(p){p.fireExpand=true}},
  {id:"hunqian",name:"魂钱串",type:"魂器",tags:["魂","击杀"],
    effect:"魂伤击杀向最近敌人跳一次固定魂伤",fn:function(p){p.soulKillChain=true}},
  {id:"lingmu",name:"铃木鱼",type:"铃具",tags:["控场","魂"],
    effect:"铃命中被减速敌人时追加小魂伤",fn:function(p){p.ringSoulHit=true}},
  {id:"fanzhao",name:"返照铜片",type:"镜片",tags:["远程","分裂"],
    effect:"折返墨迹命中后留下小范围墨爆",fn:function(p){p.bounceExplosion=true}},
  {id:"guxue",name:"骨血墨",type:"禁物",tags:["诅咒","暴击"],
    effect:"暴击率+18%，非暴击伤害-12%",fn:function(p){p.stats.critRate+=0.18;p.guxuePenalty=true}},
  {id:"shouyin",name:"收阴袋",type:"袋具",tags:["生存","击杀"],
    effect:"连续击杀积攒护盾，受击清空层数",fn:function(p){p.killShield=true}},
  {id:"fengma",name:"风行纸马",type:"纸器",tags:["机动","闪避"],
    effect:"移速越高闪避冷却越短",fn:function(p){p.dodgeSpdScale=true}},
  {id:"dengxin",name:"灯油旧芯",type:"灯具",tags:["火","生存"],
    effect:"站在火场上每秒回复3HP",fn:function(p){p.fireHeal=3}},
  {id:"judou",name:"聚灵墨斗",type:"文房",tags:["法术","魂"],
    effect:"弹道体积+40%",fn:function(p){p.stats.projSize+=0.4}},
  {id:"jijiu",name:"急就章",type:"文书",tags:["法术","攻速"],
    effect:"攻速+20%",fn:function(p){p.stats.atkSpd-=0.2}},
  {id:"zhiyuan",name:"纸鸢引",type:"纸器",tags:["召物","远程"],
    effect:"每击杀5敌生成追踪纸鸢",fn:function(p){p.summonKite=true;p.kiteKills=0}},
  {id:"liebing",name:"裂冰诀",type:"祠器",tags:["冰","暴击"],
    effect:"暴击时在目标位置留下冰冻区域",fn:function(p){p.frostOnCrit=true}},
  {id:"moyaling",name:"墨鸦翎",type:"羽器",tags:["机动","远程"],
    effect:"移速+12%，击杀后攻速大幅提升",fn:function(p){p.stats.spd+=0.12;p.killAtkSpd=true}},
  {id:"shixin",name:"石心",type:"护具",tags:["生存","近战"],
    effect:"防御+18%，移速-6%",fn:function(p){p.stats.def+=0.18;p.stats.spd-=0.06}},
  {id:"yujinshan",name:"余烬扇",type:"火具",tags:["火","生存"],
    effect:"站在火场上每秒回复3HP，若已有磷火则火场扩大",fn:function(p){p.fireHeal=(p.fireHeal||0)+3;if(p.fireOnKill)p.fireExpand=true}},
  {id:"fengmofu",name:"封魔符",type:"符物",tags:["控场","法术"],
    effect:"攻击减速效果提升至35%",fn:function(p){p.slowOnHit=Math.max(p.slowOnHit||0,0.35)}},
  {id:"huihunxiang",name:"回魂香",type:"香具",tags:["生存","击杀"],
    effect:"击杀回复3HP，击杀后短暂加速",fn:function(p){p.killHeal=(p.killHeal||0)+3;p.killSpeed=true}},
  {id:"pilimu",name:"霹雳木",type:"雷具",tags:["法术","攻速"],
    effect:"击杀后攻速大幅提升，基础攻速+12%",fn:function(p){p.killAtkSpd=true;p.stats.atkSpd-=0.12}},
  {id:"hanxingtie",name:"寒星铁",type:"铁器",tags:["冰","暴击"],
    effect:"暴击时在目标位置留下冰冻区域，暴击率+10%",fn:function(p){p.frostOnCrit=true;p.stats.critRate+=0.1}},
  {id:"mojiaojin",name:"墨蛟筋",type:"蛟具",tags:["远程","机动"],
    effect:"移速+12%，弹道体积+25%",fn:function(p){p.stats.spd+=0.12;p.stats.projSize+=0.25}},
  {id:"tunmofu",name:"吞魔符",type:"符物",tags:["击杀","生存"],
    effect:"击杀回复4HP，受击反弹20%伤害",fn:function(p){p.killHeal=(p.killHeal||0)+4;p.thorns=(p.thorns||0)+0.2}},
  {id:"jingxinzhou",name:"静心咒",type:"经咒",tags:["生存","控场"],
    effect:"替身吸收20伤害，防御+12%",fn:function(p){p.decoyHP=(p.decoyHP||0)+20;p.stats.def+=0.12}},
  {id:"pojunfu",name:"破军符",type:"符物",tags:["近战","暴击"],
    effect:"连续命中同一目标伤害递增，击杀后攻速大幅提升",fn:function(p){p.comboDmg=true;p.killAtkSpd=true}},
  {id:"mogangyin",name:"墨罡印",type:"印具",tags:["控场","远程"],
    effect:"弹道命中减速35%，弹道体积+15%",fn:function(p){p.slowOnHit=Math.max(p.slowOnHit||0,0.35);p.stats.projSize+=0.15}},
  {id:"lianhuanfu",name:"连环符",type:"符物",tags:["魂","击杀"],
    effect:"魂伤+10，击杀后魂链跳伤+1",fn:function(p){p.soulDmg=(p.soulDmg||0)+10;p.soulKillChain=true}},
  {id:"yanmoyan",name:"炎墨砚",type:"文房",tags:["火","击杀"],
    effect:"击杀留磷火，火场击杀扩大火场",fn:function(p){p.fireOnKill=true;p.fireExpand=true}},
  {id:"binghe",name:"冰核",type:"冰具",tags:["冰","暴击"],
    effect:"攻击减速提升至45%，暴击率+8%",fn:function(p){p.slowOnHit=Math.max(p.slowOnHit||0,0.45);p.stats.critRate+=0.08}},
  {id:"houmo",name:"厚墨",type:"墨具",tags:["远程","暴击"],
    effect:"伤害+20%，弹道体积+10%（体积越大越强）",fn:function(p){p.stats.dmg+=0.2;p.stats.projSize+=0.1}},
  {id:"molonglin",name:"墨龙鳞",type:"护具",tags:["生存","机动"],
    effect:"防御+20%，移速+6%（抵消石心减速）",fn:function(p){p.stats.def+=0.2;p.stats.spd+=0.06}},
  {id:"mojiangling",name:"墨将令",type:"令器",tags:["击杀","法术"],
    effect:"击杀精英敌人时爆发墨汁，对周围造成范围伤害",fn:function(p){p.eliteKillBurst=true}},
  {id:"guishouyin",name:"鬼手印",type:"印具",tags:["闪避","魂"],
    effect:"完美闪避时吸取最近敌人灵魂，回复生命并造成魂伤",fn:function(p){p.dodgeSoulGrab=true}},
  {id:"zhiyanwen",name:"纸鸢纹",type:"纸器",tags:["远程","控场"],
    effect:"弹道命中留下扩散减速墨圈",fn:function(p){p.projSlowField=true}},
  {id:"shiguping",name:"噬蛊瓶",type:"蛊器",tags:["生存","火"],
    effect:"站在毒场上回复生命而非受伤，毒场半径+30%",fn:function(p){p.poisonHeal=true}},
  {id:"yexingyi",name:"夜行衣",type:"隐具",tags:["闪避","机动"],
    effect:"迷雾中增伤+30%，魂球击中回血而非受伤",fn:function(p){p.fogBonus=true;p.soulOrbHeal=true}},
  {id:"hunsuolian",name:"魂锁链",type:"链器",tags:["处决","击杀"],
    effect:"连斩每层额外+3%伤害，十连斩以上暴击率+15%",fn:function(p){p.comboDmgBonus=true}},
  {id:"molingyu",name:"墨灵玉",type:"玉器",tags:["召物","魂"],
    effect:"召唤墨灵环绕，自动攻击附近敌人",fn:function(p){p.hasInkSpirit=true;p.inkSpiritCount=(p.inkSpiritCount||0)+1}},
  {id:"molingqi",name:"墨灵契",type:"契器",tags:["召物","魂"],
    effect:"墨灵伤害+50%，墨灵数量+1",fn:function(p){p.hasInkSpirit=true;p.inkSpiritCount=(p.inkSpiritCount||0)+2;p.spiritDmgBonus=(p.spiritDmgBonus||0)+0.5}},
  {id:"baomo",name:"爆墨灵",type:"遗物",tags:["召物","爆炸","火"],
    effect:"墨灵攻击时引发范围爆炸",fn:function(p){p.spiritExplode=true}},
  {id:"yumo",name:"愈墨灵",type:"遗物",tags:["召物","治疗"],
    effect:"墨灵击杀时为你回复3HP",fn:function(p){p.spiritHeal=true}},
  {id:"hanmo",name:"寒墨灵",type:"遗物",tags:["召物","冰"],
    effect:"墨灵攻击附加30%减速，持续1.5秒",fn:function(p){p.spiritSlow=true}},
  {id:"fenmo",name:"分墨灵",type:"遗物",tags:["召物","分裂","法术"],
    effect:"墨灵数量+2",fn:function(p){p.inkSpiritCount=(p.inkSpiritCount||0)+2}},
  {id:"powangtong",name:"破妄瞳",type:"瞳器",tags:["处决","暴击"],
    effect:"首次攻击现形画皮必暴击+50%伤害，暴击率+5%",fn:function(p){p.mimicFirstCrit=true;p.stats.critRate+=0.05}},
  {id:"zhifan",name:"蛭反",type:"蛊器",tags:["生存","反击"],
    effect:"被墨蛭吸附时攻速+35%伤害+25%",fn:function(p){p.leechBuff=true}},
  {id:"moshouzhen",name:"墨守阵",type:"阵器",tags:["生存","控场"],
    effect:"静止1秒后生成墨守圈，圈内减伤25%",fn:function(p){p.defFormation=true}},
  {id:"mogongzhen",name:"墨攻阵",type:"阵器",tags:["击杀","法术"],
    effect:"每击杀3敌释放墨爆脉冲，伤害=攻击力×2",fn:function(p){p.atkFormation=true}},
  {id:"zhenyan",name:"阵眼",type:"阵器",tags:["控场","生存"],
    effect:"墨阵范围+40%，触发条件减半",fn:function(p){p.formBoost=true}},
  {id:"mojing",name:"墨镜",type:"镜器",tags:["防御","法术"],
    effect:"30%概率反弹敌方弹道，反弹伤害翻倍",fn:function(p){p.reflectChance=(p.reflectChance||0)+0.3;p.reflectDmgMult=(p.reflectDmgMult||0)+1}},
  {id:"huichunzhen",name:"回春阵",type:"阵器",tags:["生存","控场"],
    effect:"静止1.2秒生成回春圈，圈内每秒回复3HP",fn:function(p){p.healFormation=true}},
  {id:"mowo",name:"墨涡",type:"阵器",tags:["击杀","控场"],
    effect:"每击杀5敌在脚下释放墨涡，牵引并伤害周围敌人",fn:function(p){p.vortexOnKill=true}},
  {id:"moxi",name:"墨吸",type:"阵器",tags:["击杀","控场"],
    effect:"击杀敌人延长所有墨阵15帧",fn:function(p){p.formationLeech=true}},
  {id:"mojia",name:"墨甲",type:"护具",tags:["生存","控场"],
    effect:"防御+15%，在墨阵内额外+15%防御",fn:function(p){p.stats.def+=0.15;p.formDef=true}},
  {id:"mobao",name:"墨爆",type:"阵器",tags:["击杀","法术"],
    effect:"墨阵消失时引爆，对范围内敌人造成伤害",fn:function(p){p.formationDetonate=true}},
  {id:"moxian",name:"墨弦",type:"阵器",tags:["法术","控场"],
    effect:"两个以上墨阵间生成墨弦，触弦敌人受伤",fn:function(p){p.inkStrings=true}},
  {id:"moding",name:"墨钉",type:"凶器",tags:["控场","近战"],
    effect:"攻击钉住首个命中敌人1.5秒，禁止移动",fn:function(p){p.attackPin=true}},
  {id:"mochen",name:"墨澄",type:"阵器",tags:["法术","控场"],
    effect:"站在墨阵内时攻速+20%",fn:function(p){p.formClarity=true}},
  {id:"motao",name:"墨涛",type:"墨具",tags:["击杀","控场"],
    effect:"击杀敌人释放墨涛，推开周围敌人",fn:function(p){p.killPulse=true}},
  {id:"molian",name:"墨涟",type:"阵器",tags:["法术","控场"],
    effect:"站在墨阵内每0.5秒释放墨涟，伤害周围敌人",fn:function(p){p.formRipple=true}},
  {id:"moyi",name:"墨移",type:"闪具",tags:["闪避","机动"],
    effect:"闪后留影，3秒内再闪回归原位",fn:function(p){p.recallDash=true}},
  {id:"moze",name:"墨泽",type:"墨具",tags:["击杀","机动"],
    effect:"击杀敌人获得3秒移速+20%",fn:function(p){p.killSpeedBurst=true}},
  {id:"moxiu",name:"墨嗅",type:"墨具",tags:["击杀","处决"],
    effect:"击杀延长连斩窗口15帧，更易维持高连斩",fn:function(p){p.scentStreak=true}},
  {id:"mowei",name:"墨威",type:"阵器",tags:["法术","击杀"],
    effect:"每个活跃墨阵+6%伤害",fn:function(p){p.formDmgBonus=true}},

  {id:"mosui",name:"墨碎",type:"凶器",tags:["暴击","溅射"],
    effect:"暴击时溅射碎片，对周围敌人造成35%伤害",fn:function(p){p.critShrapnel=true}},
  {id:"moshi",name:"墨蚀",type:"墨具",tags:["持续","法术"],
    effect:"攻击附加墨蚀，每秒2点伤害持续5秒，可叠3层",fn:function(p){p.corrosive=true}},
  {id:"monu",name:"墨怒",type:"墨具",tags:["生命","爆发"],
    effect:"生命低于50%时，伤害+25%移速+15%",fn:function(p){p.lowHpFury=true}},
  // v4.3 new relics
  {id:"hunfanling",name:"魂幡灵",type:"幡器",tags:["召物","法术"],
    effect:"幡的魂弹伤害+40%，寻敌范围+50",fn:function(p){p.bannerDmgMult=(p.bannerDmgMult||1)+0.4;p.bannerRangeBonus=(p.bannerRangeBonus||0)+50}},
  {id:"moshizhu",name:"墨师珠",type:"珠玉",tags:["法术","击杀"],
    effect:"击杀时在敌人位置生成微型墨池，减速附近敌人",fn:function(p){p.killSlowPool=true}},
  {id:"xianluowen",name:"仙螺纹",type:"螺器",tags:["控场","召物"],
    effect:"铃铛范围+20%，幡的魂弹附带0.3秒减速",fn:function(p){p.stats.range+=0.2;p.bannerSpiritSlow=true}},
  // v4.7 new relics
  {id:"mojingsui",name:"墨镜碎影",type:"镜器",tags:["防御","法术"],
    effect:"站定0.5秒后自动反射最近一颗敌方弹道，冷却4秒",fn:function(p){p.autoReflect=true}},
  {id:"jiuzhuanmofu",name:"九转墨符",type:"符器",tags:["法术","爆发"],
    effect:"每命中6次敌人，下次攻击变为全方向AOE爆发",fn:function(p){p.hasNineSeal=true;p.nineSealCount=0;p.nineSealReady=false}},
  // v4.13 new relic
  {id:"mojicanbu",name:"墨迹残步",type:"步具",tags:["机动","爆发"],
    effect:"连续移动充能，停下时释放墨爆（充能越久范围越大，最大120帧蓄满）",fn:function(p){p.moveChargeMax=true;p.moveChargeT=0}},
  // v4.14 new relics
  {id:"huanguquan",name:"还骨泉",type:"泉器",tags:["治疗","生存"],
    effect:"击杀敌人有15%概率回复3点生命",fn:function(p){p.killHealChance=(p.killHealChance||0)+0.15;p.killHealAmt=(p.killHealAmt||0)+3}},
  {id:"mosancui",name:"墨散淬",type:"淬具",tags:["溅射","近战"],
    effect:"近战攻击命中时向四周溅射小墨滴，造成30%伤害",fn:function(p){p.meleeSplash=true;p.meleeSplashRatio=(p.meleeSplashRatio||0)+0.3}},
  {id:"moboaoyin",name:"墨爆印",type:"印具",tags:["爆炸","近战"],
    effect:"近战武器击杀敌人时引发墨爆，对周围50范围内敌人造成40%攻击力伤害",fn:function(p){p.killExplode=true;p.killExplodeRatio=(p.killExplodeRatio||0)+0.4}},
  {id:"shimoChi",name:"蚀墨池",type:"池具",tags:["持续","击杀"],
    effect:"击杀敌人留下蚀墨区域，持续3秒对范围内敌人造成伤害并减速",fn:function(p){p.killDotZone=true;p.killDotDmg=(p.killDotDmg||0)+1}},
  {id:"guxuquan",name:"骨续泉",type:"泉器",tags:["生命","生存"],
    effect:"每清一波，最大生命+2（最多+10），同时回复等量生命",fn:function(p){p.waveHpBonus=true;p.waveHpMax=(p.waveHpMax||0)+10;p.waveHpGain=(p.waveHpGain||0)+2}},
  {id:"bingmobi",name:"冰墨壁",type:"壁具",tags:["防御","冰"],
    effect:"受伤时在自身周围生成冰墨区域，减速附近敌人3秒",fn:function(p){p.hurtFrost=true}},
  {id:"moquanyan",name:"墨泉眼",type:"泉具",tags:["治疗","生存"],
    effect:"波次结束时若生命低于50%，回复20%最大生命",fn:function(p){p.lowHpWaveHeal=true}},
  {id:"moyanqian",name:"墨焰溅",type:"溅具",tags:["溅射","火"],
    effect:"火焰击杀敌人时向四周溅射火滴，对附近敌人造成20%攻击力的火焰伤害",fn:function(p){p.fireSplash=true;p.fireSplashRatio=(p.fireSplashRatio||0)+0.2}},
  {id:"mohuoyan",name:"墨火眼",type:"眼具",tags:["爆炸","火"],
    effect:"暴击时产生小范围爆炸，对周围敌人造成25%攻击力伤害",fn:function(p){p.critExplosion=true;p.critExplosionRatio=(p.critExplosionRatio||0)+0.25}},
  {id:"mofutan",name:"墨符坛",type:"坛具",tags:["持续","法术"],
    effect:"攻击命中时在目标位置留下墨符，持续2秒对范围内敌人造成伤害",fn:function(p){p.hitDot=true;p.hitDotDmg=(p.hitDotDmg||0)+1;p.hitDotLife=(p.hitDotLife||0)+60}},
  {id:"mohundan",name:"墨魂丹",type:"丹具",tags:["生命","爆发"],
    effect:"生命低于25%时，攻击力+50%持续5秒，每波触发一次",fn:function(p){p.lowHpBurst=true}},
  {id:"mobaodan",name:"墨爆弹",type:"弹具",tags:["爆炸","爆发"],
    effect:"对HP低于30%的敌人造成伤害时自动引爆，对周围造成50%攻击力伤害",fn:function(p){p.executeExplode=true;p.executeExplodeRatio=(p.executeExplodeRatio||0)+0.5}},
  {id:"moshiyu",name:"墨蚀域",type:"域具",tags:["持续","溅射"],
    effect:"攻击命中时留下持续3秒的墨蚀区域，每秒对范围内敌人造成溅射伤害",fn:function(p){p.splashDot=true;p.splashDotDmg=(p.splashDotDmg||0)+1;p.splashDotLife=(p.splashDotLife||0)+180}},
  {id:"xumingmo",name:"续命墨",type:"墨具",tags:["治疗","生命"],
    effect:"击杀敌人时35%几率回复4点生命，溢出治疗转化为临时护盾",fn:function(p){p.killHealChance=(p.killHealChance||0)+0.35;p.killHealAmt=(p.killHealAmt||0)+4;p.healToShield=true}},
  {id:"moliefu",name:"墨裂符",type:"符具",tags:["分裂","法术"],
    effect:"攻击命中时20%几率分裂出额外弹幕，追踪附近敌人",fn:function(p){p.splitOnHit=true;p.splitChance=(p.splitChance||0)+0.2}},
  {id:"motiebi",name:"墨铁壁",type:"壁具",tags:["防御","反击"],
    effect:"受击后获得1秒无敌+向周围释放反击波",fn:function(p){p.hurtRetaliate=true;p.hurtRetaliateDmg=(p.hurtRetaliateDmg||0)+5}},
  {id:"mangmou",name:"盲牟",type:"瞳器",tags:["诅咒","爆发"],
    effect:"致盲期间攻击伤害+60%（致盲反而变强）",fn:function(p){p.blindDmgBoost=(p.blindDmgBoost||0)+0.6}},
  {id:"molianbao",name:"墨涟爆",type:"爆具",tags:["溅射","爆炸"],
    effect:"溅射击杀敌人时有40%概率触发二次墨爆，对周围造成35%攻击力伤害",fn:function(p){p.splashDeathBoom=true;p.splashDeathBoomChance=(p.splashDeathBoomChance||0)+0.4;p.splashDeathBoomRatio=(p.splashDeathBoomRatio||0)+0.35}},
  {id:"molielian",name:"墨裂涟",type:"漪具",tags:["分裂","溅射"],
    effect:"溅射伤害命中时蓄墨涟层数（最多3层），下次攻击消耗层数，每层+8%伤害",fn:function(p){p.splashRippleStack=true;p.splashRippleMax=3;p.splashRippleBonus=0.08}},
  {id:"mohuafeng",name:"墨化蜂",type:"墨具",tags:["分裂","持续"],
    effect:"命中时20%几率向附近敌人发射追踪弹，并在落点留下持续伤害墨域",fn:function(p){p.splitDot=true}},
  {id:"moxizhu",name:"墨息珠",type:"饰具",tags:["持续","生命"],
    effect:"击杀敌人后6秒内每秒恢复2点生命",fn:function(p){p.breathOnKill=true}},
  {id:"mojiedun",name:"墨棘盾",type:"盾具",tags:["溅射","防御"],
    effect:"受伤时向周围溅射墨棘，造成范围伤害",fn:function(p){p.hurtSplash=true;p.hurtSplashDmg=(p.hurtSplashDmg||0)+5}},
  {id:"moobaohun",name:"墨爆魂",type:"魂器",tags:["爆炸","生命"],
    effect:"低血量时击杀敌人回复8点生命",fn:function(p){p.killBurstHeal=true}},
  {id:"moxuexing",name:"墨血星",type:"墨具",tags:["溅射","生命"],
    effect:"击杀小怪时溅射墨血伤敌，回复2点生命",fn:function(p){p.killSplashHeal=true}},
  {id:"molieshengfu",name:"墨裂生符",type:"符具",tags:["分裂","生命"],
    effect:"分裂弹命中敌人时18%几率回复1点生命",fn:function(p){p.splitHitHeal=true}},
  {id:"mohunjia",name:"墨魂甲",type:"甲具",tags:["持续","防御"],
    effect:"受伤后3秒内再受伤减伤50%，每次受伤刷新时长",fn:function(p){p.hurtShieldActive=true}},
  {id:"mosanzhi",name:"墨散芝",type:"芝具",tags:["治疗","溅射"],
    effect:"击杀小怪时在较大范围溅射两次轻伤并回复3点生命",fn:function(p){p.killSplashWideHeal=true}},
  {id:"molefubao",name:"墨烈符爆",type:"符具",tags:["分裂","爆炸"],
    effect:"分裂命中25%几率在敌人身上引爆小型墨焰，对周围敌人造成主伤45%溅射",fn:function(p){p.splitBoomOnHit=true}},
  {id:"mozhenjia",name:"墨震甲",type:"甲具",tags:["爆炸","防御"],
    effect:"受Boss伤害-30%，同时向周围墨震爆裂反击6点",fn:function(p){p.bossHurtGuard=true}},
  {id:"moyingyi",name:"墨盈溢",type:"墨具",tags:["治疗","爆炸"],
    effect:"满血时受到治疗，溢出部分转化为3倍伤害墨爆溅射到周围",fn:function(p){p.healOverflowBoom=true}},
  {id:"mofenyu",name:"墨焚域",type:"域具",tags:["持续","爆炸"],
    effect:"持续伤害累计30点后，该敌人引爆，对周围造成累计伤害一半的AOE",fn:function(p){p.dotAccumBoom=true}},
  {id:"molieshengjia",name:"墨裂盛甲",type:"甲具",tags:["分裂","防御"],
    effect:"分裂弹命中敌人后2秒内受伤减伤35%，每次分裂命中刷新时长",fn:function(p){p.splitShieldActive=true}},
  {id:"moshengfang",name:"墨生防",type:"甲具",tags:["生命","防御"],
    effect:"血量≥90%时受到伤害减免25%",fn:function(p){p.fullHpDefense=true}},
  {id:"moshengzhi",name:"墨生芝",type:"芝具",tags:["分裂","治疗"],
    effect:"分裂弹命中敌人时15%几率回复1点生命",fn:function(p){p.splitHealOnHit=true}},
  {id:"mohushen",name:"墨护身",type:"护具",tags:["治疗","防御"],effect:"防御+15%，击杀回复3HP",fn:function(p){p.stats.def+=0.15;p.killHeal=(p.killHeal||0)+3}},
  {id:"mochizhu",name:"墨持珠",type:"珠玉",tags:["持续","治疗"],effect:"站在火场上每秒+2HP，防御+8%",fn:function(p){p.fireHeal=(p.fireHeal||0)+2;p.stats.def+=0.08}},
  {id:"mowushi",name:"墨雾蚀",type:"雾具",tags:["生存","控场"],effect:"攻击减速提升至30%，防御+10%",fn:function(p){p.slowOnHit=Math.max(p.slowOnHit||0,0.3);p.stats.def+=0.1}},
  {id:"moqianli",name:"墨千里",type:"羽器",tags:["机动","暴击"],effect:"移速+15%，暴击率+8%",fn:function(p){p.stats.spd+=0.15;p.stats.critRate+=0.08}},
  {id:"molianji",name:"墨连击",type:"刃具",tags:["近战","攻速"],effect:"攻速+15%，多重+1",fn:function(p){p.stats.atkSpd-=0.15;p.stats.multi+=1}},
  {id:"monuhun",name:"墨怒魂",type:"魂器",tags:["魂","生存"],effect:"魂伤+5，防御+10%",fn:function(p){p.soulDmg+=5;p.stats.def+=0.1}},
  {id:"mozhanhun",name:"墨斩魂",type:"刃具",tags:["近战","处决"],effect:"伤害+25%，暴击伤害+40%",fn:function(p){p.stats.dmg+=0.25;p.stats.critDmg+=0.4}},
  {id:"monuxing",name:"墨怒行",type:"行具",tags:["机动","暴击"],effect:"移速+10%，暴击率+15%",fn:function(p){p.stats.spd+=0.1;p.stats.critRate+=0.15}},
  {id:"moshouren",name:"墨守忍",type:"甲具",tags:["生存","反击"],effect:"防御+20%，反弹伤害+30%",fn:function(p){p.stats.def+=0.2;p.thorns=(p.thorns||0)+0.3}},
  {id:"moyinfu",name:"墨阴符",type:"符物",tags:["击杀","魂"],effect:"魂伤击杀敌人时额外回复1点生命",fn:function(p){p.yinFuHeal=true}},
  {id:"monuyan",name:"墨怒焰",type:"火具",tags:["火","暴击"],effect:"暴击率+12%，暴击伤害+30%",fn:function(p){p.stats.critRate+=0.12;p.stats.critDmg+=0.3}},
  {id:"mobingxin",name:"墨冰心",type:"心具",tags:["冰","生存"],effect:"防御+12%，攻击减速+20%",fn:function(p){p.stats.def+=0.12;p.slowOnHit=Math.max(p.slowOnHit||0,0.2)}},
  {id:"moruyu",name:"墨濡羽",type:"羽具",tags:["机动","远程"],effect:"弹速+20%，移速+8%",fn:function(p){p.stats.projSpd=(p.stats.projSpd||1)+0.2;p.stats.spd+=0.08}},
  {id:"mojingchao",name:"墨静潮",type:"潮具",tags:["控场","魂"],effect:"攻击范围+20%，魂伤+3",fn:function(p){p.stats.range+=0.2;p.soulDmg+=3}},
  {id:"mohongyu",name:"墨宏域",type:"域具",tags:["控场","攻速"],effect:"范围+15%，攻速+10%",fn:function(p){p.stats.range+=0.15;p.stats.atkSpd-=0.1}},
  {id:"mojianqi",name:"墨剑气",type:"剑具",tags:["近战","处决"],effect:"伤害+20%，移速+8%",fn:function(p){p.stats.dmg+=0.2;p.stats.spd+=0.08}},
  {id:"momengen",name:"墨蒙眼",type:"禁物",tags:["诅咒","处决"],effect:"伤害+35%，但防御-15%",fn:function(p){p.stats.dmg+=0.35;p.stats.def-=0.15}},
  {id:"moyanpai",name:"墨烟牌",type:"牌具",tags:["生存","控场"],effect:"防御+15%，减速+15%",fn:function(p){p.stats.def+=0.15;p.slowOnHit=Math.max(p.slowOnHit||0,0.15)}},
  {id:"moguangmu",name:"墨光幕",type:"幕具",tags:["闪避","防御"],effect:"防御+12%，反弹+10%",fn:function(p){p.stats.def+=0.12;p.thorns=(p.thorns||0)+0.1}},
  {id:"mofanglei",name:"墨方雷",type:"雷具",tags:["法术","暴击"],effect:"暴击率+10%，弹道体积+20%",fn:function(p){p.stats.critRate+=0.1;p.stats.projSize+=0.2}},
  {id:"moshouhuo",name:"墨守火",type:"火具",tags:["火","生存"],effect:"移速+12%，火场每秒+1HP",fn:function(p){p.stats.spd+=0.12;p.fireHeal=(p.fireHeal||0)+1}},
  {id:"mojihong",name:"墨霁虹",type:"虹具",tags:["魂","远程"],effect:"魂伤+4，弹道体积+15%",fn:function(p){p.soulDmg+=4;p.stats.projSize+=0.15}},
  {id:"motiejie",name:"墨铁界",type:"甲具",tags:["冰","反击"],effect:"减速+18%，反弹+25%",fn:function(p){p.slowOnHit=Math.max(p.slowOnHit||0,0.18);p.thorns=(p.thorns||0)+0.25}},
  {id:"mocanxue",name:"墨残血",type:"禁物",tags:["诅咒","暴击"],effect:"暴击伤害+50%，受伤+10%",fn:function(p){p.stats.critDmg+=0.5;p.extraDmgTaken=(p.extraDmgTaken||0)+0.1}},
  {id:"mopeng",name:"墨篷",type:"篷具",tags:["闪避","机动"],effect:"移速+18%，暴击率+5%",fn:function(p){p.stats.spd+=0.18;p.stats.critRate+=0.05}},
  {id:"mojianshi",name:"墨间石",type:"石具",tags:["生存","击杀"],effect:"防御+10%，击杀回2HP",fn:function(p){p.stats.def+=0.1;p.killHeal=(p.killHeal||0)+2}},
  {id:"moyunshi",name:"墨云石",type:"石具",tags:["生存","机动"],effect:"防御+10%，移速+6%",fn:function(p){p.stats.def+=0.1;p.stats.spd+=0.06}},
  {id:"mohanfeng",name:"墨寒风",type:"风具",tags:["冰","机动"],effect:"移速+10%，减速+12%",fn:function(p){p.stats.spd+=0.1;p.slowOnHit=Math.max(p.slowOnHit||0,0.12)}},
  {id:"moxue",name:"墨血",type:"禁物",tags:["诅咒","魂"],effect:"魂伤+6，但受伤+15%",fn:function(p){p.soulDmg+=6;p.extraDmgTaken=(p.extraDmgTaken||0)+0.15}},
  {id:"mojinbiao",name:"墨金镖",type:"镖具",tags:["远程","暴击"],effect:"弹道穿透，暴击率+8%",fn:function(p){p.projPierce=true;p.stats.critRate+=0.08}},
  {id:"mozhendang",name:"墨震铛",type:"铛具",tags:["控场","处决"],effect:"范围+18%，伤害+12%",fn:function(p){p.stats.range+=0.18;p.stats.dmg+=0.12}},
  {id:"mojieguang",name:"墨劫光",type:"光具",tags:["暴击","机动"],effect:"暴击率+10%，移速+10%（helper 测试）",fn:function(p){p.stats.critRate+=0.1;p.stats.spd+=0.1}},
  {id:"mohunyin",name:"墨魂引",type:"灵具",tags:["魂","击杀"],effect:"击杀敌人时发射追踪弹",fn:function(p){p.soulKill=true}},
  {id:"mozhoukai",name:"墨咒铠",type:"壁具",tags:["诅咒","生存"],effect:"受击时短暂无敌并反伤周围敌人",fn:function(p){p.curseSurv=true}},
  {id:"mofendan",name:"墨焚弹",type:"弹具",tags:["远程","火"],effect:"远程命中15%几率点燃敌人",fn:function(p){p.rangedFire=true}},
  {id:"mojuling",name:"墨聚灵",type:"聚具",tags:["召唤","爆发"],effect:"墨魂≥3只时伤害+20%",fn:function(p){p.summonBurst=true}},
  {id:"mochongying",name:"墨冲影",type:"影具",tags:["冲刺","反击"],effect:"冲刺时对身边敌人造成反伤",fn:function(p){p.dashRetaliate=true}},
  {id:"mojifeng",name:"墨疾风",type:"风具",tags:["近战","机动"],effect:"近战击杀获得攻速+移速加成",fn:function(p){p.meleeMobility=true}},
  {id:"mojiehuan",name:"墨劫环",type:"环具",tags:["范围","击杀"],effect:"击杀敌人时对周围造成范围伤害",fn:function(p){p.killAOE=true}},
  {id:"moxueren",name:"墨血刃",type:"刃具",tags:["暴击","治疗"],effect:"暴击时回复少量生命",fn:function(p){p.critHeal=true}},
  {id:"moxuanbu",name:"墨旋步",type:"步具",tags:["机动","溅射"],effect:"闪避时在原位留下范围伤害区",fn:function(p){p.dodgeSplash=true}},
  {id:"mozhouxin",name:"墨咒心",type:"心具",tags:["生命","诅咒"],effect:"最大生命+20，高血量时伤害+10%",fn:function(p){p.curseHeart=true}},
  {id:"monicizhou",name:"墨逆咒",type:"咒具",tags:["反击","法术"],effect:"受击时向最近敌人发射追踪弹",fn:function(p){p.counterSpell=true}},
  {id:"moshenglian",name:"墨生莲",type:"莲具",tags:["爆发","治疗"],effect:"濒死时爆发回血并伤害周围敌人",fn:function(p){p.burstHeal=true}},
  {id:"moyanbao",name:"墨焰爆",type:"焰具",tags:["溅射","火"],effect:"命中时概率生成火焰区",fn:function(p){p.splashFire=true}},
  {id:"moxuming",name:"墨续命",type:"命具",tags:["击杀","生存"],effect:"击杀敌人时回复2血并获得短暂无敌",fn:function(p){p.killSurvive=true}},
  {id:"mohunbu",name:"墨魂步",type:"步具",tags:["魂","机动"],effect:"每拥有一个墨魂移速+3%",fn:function(p){p.spiritSpeed=true}},
  {id:"mofenxin",name:"墨焚心",type:"心具",tags:["火","爆发"],effect:"低血时攻击附带火焰爆发",fn:function(p){p.fireBurst=true}},
  {id:"moyaohun",name:"墨遥魂",type:"魂具",tags:["召唤","远程"],effect:"远程击杀敌人时墨魂上限+1",fn:function(p){p.rangedKillSpirit=true;p.inkSpiritMax=(p.inkSpiritMax||0)+1}},
  {id:"mohunsi",name:"墨魂嗣",type:"魂具",tags:["召唤","魂"],effect:"墨魂存在时魂伤+2",fn:function(p){p.soulHitBoost=true;p.stats.soulDmg=(p.stats.soulDmg||0)+2}},
  {id:"mofenying",name:"墨焚影",type:"步具",tags:["冲刺","火"],effect:"冲刺时路径留下墨焰",fn:function(p){p.dashFireTrail=true}},
  {id:"moxunren",name:"墨迅刃",type:"刃具",tags:["冲刺","暴击"],effect:"冲刺后暴击率+15%",fn:function(p){p.dashCritBoost=true;p.stats.critRate=(p.stats.critRate||0)+0.15}},
  {id:"moguangshi",name:"墨广蚀",type:"域具",tags:["范围","持续"],effect:"范围+15%，攻击附带持续伤害",fn:function(p){p.aoeDotHit=true;p.stats.area=(p.stats.area||1)+0.15}},
  {id:"mobiyin",name:"墨庇印",type:"护具",tags:["范围","防御"],effect:"范围+10%，防御+12%",fn:function(p){p.aoeGuardBond=true;p.stats.area=(p.stats.area||1)+0.1;p.stats.def=(p.stats.def||0)+0.12}},
  {id:"mozhaojun",name:"墨召魂引",type:"法具",tags:["召唤","击杀"],effect:"击杀时25%概率召唤墨魂",fn:function(p){p.killSummonSpirit=true;p.killSummonChance=0.25}},
  {id:"mosufeng",name:"墨速锋",type:"锋具",tags:["攻速","暴击"],effect:"攻速+10%，暴击率+8%",fn:function(p){p.mosufengBond=true;p.stats.spd=(p.stats.spd||1)+0.1;p.stats.critRate=(p.stats.critRate||0)+0.08}},
  {id:"mofanyu",name:"墨泛域",type:"域具",tags:["范围","控场"],effect:"范围+12%，命中减速+0.15",fn:function(p){p.mofanyuBond=true;p.stats.area=(p.stats.area||1)+0.12;p.slowOnHit=(p.slowOnHit||0)+0.15}},
  {id:"mokuaihun",name:"墨快魂",type:"魂具",tags:["攻速","魂"],effect:"攻速+10%，魂伤+2",fn:function(p){p.mokuaihunBond=true;p.stats.spd=(p.stats.spd||1)+0.1;p.stats.soulDmg=(p.stats.soulDmg||0)+2}},
  {id:"mochongguang",name:"墨冲光",type:"光具",tags:["冲刺","暴击"],effect:"暴击率+8%，攻速+5%",fn:function(p){p.mochongguangBond=true;p.stats.critRate=(p.stats.critRate||0)+0.08;p.stats.spd=(p.stats.spd||1)+0.05}},
  {id:"mozhenlianhuan",name:"墨阵连环",type:"阵具",tags:["范围","持续"],effect:"范围+15%，攻击附带持续墨蚀",fn:function(p){p.mozhenlianhuan=true;p.stats.area=(p.stats.area||1)+0.15;p.hitDot=true;p.hitDotDmg=(p.hitDotDmg||0)+2;p.hitDotLife=(p.hitDotLife||0)+240}},
  {id:"mobaoliansu",name:"墨爆连锁",type:"爆具",tags:["爆炸","溅射"],effect:"溅射伤害+20%，爆炸击杀时对周围再溅射",fn:function(p){p.mobaoliansu=true;p.splashDeathBoom=true;p.splashDeathBoomChance=(p.splashDeathBoomChance||0)+0.2;p.splashDeathBoomRatio=(p.splashDeathBoomRatio||0)+0.35}}
  ,
  {id:"moduanren",name:"墨断刃",type:"刃具",tags:["近战","暴击"],effect:"近战暴击时向前突进并造成额外伤害",prereq:"moduanren",fn:function(p){p.meleeCritDash=true;p.meleeCritDashDmg=8}},
  {id:"moxuejian",name:"墨血剑",type:"剑具",tags:["近战","生命"],effect:"近战命中时回复1HP，但受伤+10%",prereq:"moxuejian",fn:function(p){p.meleeHitHeal=true;p.extraDmgTaken=(p.extraDmgTaken||0)+0.1}},
  {id:"moguidan",name:"墨鬼弹",type:"弹具",tags:["远程","溅射"],effect:"远程命中时溅射周围敌人20%伤害",prereq:"moguidan",fn:function(p){p.rangedSplash=true;p.rangedSplashRatio=0.2}},
  {id:"mosheying",name:"墨射影",type:"影具",tags:["远程","机动"],effect:"远程击杀时获得1.5秒移速加成",prereq:"mosheying",fn:function(p){p.rangedKillSpeed=true}},
  {id:"mohunyin",name:"墨魂音",type:"铃具",tags:["控场","魂"],effect:"铃声波命中时附加魂伤3点",prereq:"mohunyin",fn:function(p){p.aoeSoulHit=true;p.aoeSoulDmg=3}},
  {id:"mozhenling",name:"墨镇灵",type:"铃具",tags:["控场","防御"],effect:"铃声波范围内减伤15%",prereq:"mozhenling",fn:function(p){p.aoeDefField=true;p.aoeDefFieldAmt=0.15}},
  {id:"moyingshan",name:"墨影伞",type:"伞具",tags:["冲刺","生存"],effect:"冲刺时留下残影反伤敌人",prereq:"moyingshan",fn:function(p){p.dashDecoyStrike=true}},
  {id:"mopofeng",name:"墨破风",type:"风具",tags:["冲刺","暴击"],effect:"冲刺后下次攻击必定暴击",prereq:"mopofeng",fn:function(p){p.dashNextCrit=true}},
  {id:"mohunzhui",name:"墨魂坠",type:"法具",tags:["召唤","爆发"],effect:"墨魂命中时15%概率爆炸",prereq:"mohunzhui",fn:function(p){p.spiritExplodeChance=(p.spiritExplodeChance||0)+0.15}},
  {id:"molianhun",name:"墨链魂",type:"魂器",tags:["召唤","魂"],effect:"墨魂击杀时回复2HP",prereq:"molianhun",fn:function(p){p.spiritKillHeal=(p.spiritKillHeal||0)+2}},
  // v13.0 新遗物 x10
  {id:"mozhuxi",name:"墨竹笛",type:"法器",tags:["控场","减益"],effect:"攻击有15%概率使敌人致盲3秒",fn:function(p){p.blindOnHit=(p.blindOnHit||0)+0.15}},
  {id:"momingzhu",name:"墨明珠",type:"宝具",tags:["暴击","法术"],effect:"暴击伤害+15%，暴击率+3%",fn:function(p){p.stats.critDmg+=0.15;p.stats.critRate=Math.min(CAPS.critRate,p.stats.critRate+0.03)}},
  {id:"moxueyu",name:"墨血玉",type:"宝具",tags:["暴击","生存"],effect:"暴击时回复1HP，连杀时翻倍",fn:function(p){p.critHealHp=(p.critHealHp||0)+1}},
  {id:"mohunshu",name:"墨魂书",type:"法器",tags:["法术","击杀"],effect:"每击杀5个敌人，下次攻击增伤+50%",fn:function(p){p.killChargeDmg=0;p.killChargeMax=5}},
  {id:"moyanluo",name:"墨烟罗",type:"防具",tags:["生存","减益"],effect:"受伤后3秒内减伤+40%",fn:function(p){p.hurtDefBoost=true;p.hurtDefAmt=0.4;p.hurtDefDur=180}},
  {id:"mozhijing",name:"墨纸镜",type:"宝具",tags:["防御","法术"],effect:"受到弹道伤害时有20%概率反弹",fn:function(p){p.reflectChance=(p.reflectChance||0)+0.2;p.reflectDmgMult=(p.reflectDmgMult||0)+0.3}},
  {id:"moyeyi",name:"墨夜衣",type:"防具",tags:["生存","机动"],effect:"静止1秒后进入隐身，移速+20%",fn:function(p){p.stealthIdle=true;p.stats.spd+=0.2}},
  {id:"mofengling",name:"墨风铃",type:"铃具",tags:["控场","减益"],effect:"敌人进入攻击范围时减速20%",fn:function(p){p.aoeSlowField=true;p.aoeSlowFieldAmt=0.2}},
  {id:"moguiyin",name:"墨鬼印",type:"法器",tags:["法术","诅咒"],effect:"伤害+25%，但受伤+15%",fn:function(p){p.stats.dmg+=0.25;p.dmgTakenMult=(p.dmgTakenMult||1)+0.15}},
  {id:"mohundeng",name:"墨魂灯",type:"宝具",tags:["召唤","生存"],effect:"每波开始召唤2个墨灵，墨灵伤害+20%",fn:function(p){p.hasInkSpirit=true;p.inkSpiritCount=(p.inkSpiritCount||0)+1;p.spiritDmgBonus=(p.spiritDmgBonus||0)+0.2}},
  {id:"mochuanshe",name:"墨穿射",type:"弹具",tags:["远程","溅射"],effect:"远程攻击命中时弹体穿透+1，溅射范围+20%",fn:function(p){p.projPierce=true;p.rangedSplashRatio=(p.rangedSplashRatio||0.2)+0.2}},
  {id:"mozhuiyu",name:"墨追羽",type:"羽具",tags:["远程","暴击"],effect:"暴击率+10%，弹速+15%",prereq:"mochuanshe",fn:function(p){p.stats.critRate+=0.10;p.stats.atkSpd+=0.15}},
  {id:"mopianxing",name:"墨流星",type:"镖具",tags:["远程","击杀"],effect:"远程击杀时向周围发射2枚追踪弹",prereq:"mochuanshe",fn:function(p){p.rangedKillSpirit=true}}
];

var EVOLUTIONS={
  melee:[
    {id:"e_pishan",name:"劈山",type:"进化",tags:["近战"],effect:"劈砍范围+30%，弧度加宽",
      fn:function(p){p.stats.range+=0.3;p.wideSlash=true}},
    {id:"e_luanwu",name:"乱舞",type:"进化",tags:["近战"],effect:"多重打击+1",
      fn:function(p){p.stats.multi+=1}},
    {id:"e_duanyue",name:"断岳",type:"进化",tags:["近战"],effect:"伤害+40%",
      fn:function(p){p.stats.dmg+=0.4}},
    {id:"e_zhemo",name:"斩魔",type:"进化",tags:["近战"],effect:"每3击释放追踪墨刃",
      fn:function(p){p.seekBlade=true}},
    {id:"e_huizhan",name:"回斩",type:"进化",tags:["近战","处决"],effect:"击杀后下次攻击伤害+45%",
      fn:function(p){p.killDmgBoost=true}},
    {id:"e_zhongjian",name:"重剑",type:"进化",tags:["近战"],effect:"伤害+50%，但攻速-10%",
      fn:function(p){p.stats.dmg+=0.5;p.stats.atkSpd+=0.1}},
    {id:"e_jianyi",name:"剑意",type:"进化",tags:["近战","暴击"],effect:"伤害+30%，暴击率+5%",
      fn:function(p){p.stats.dmg+=0.3;p.stats.critRate+=0.05}},
    {id:"e_jianfeng",name:"剑锋",type:"进化",tags:["近战","控场"],effect:"攻击范围+20%，攻速-10%",
      fn:function(p){p.stats.range+=0.2;p.stats.atkSpd+=0.1}},
    {id:"e_xiejian",name:"邪剑",type:"进化",tags:["近战","诅咒"],effect:"伤害+60%，但防御-20%",fn:function(p){p.stats.dmg+=0.6;p.stats.def-=0.2}},
    {id:"e_qijian",name:"气剑",type:"进化",tags:["近战","机动"],effect:"攻击释放气浪，远程命中敌人",fn:function(p){p.meleeWave=true}}
  ],
  ranged:[
    {id:"e_lianzhu",name:"连珠",type:"进化",tags:["远程"],effect:"弹数+1",
      fn:function(p){p.stats.multi+=1}},
    {id:"e_guanjia",name:"贯甲",type:"进化",tags:["远程"],effect:"弹道穿透敌人",
      fn:function(p){p.projPierce=true}},
    {id:"e_baolie",name:"爆裂",type:"进化",tags:["远程"],effect:"弹道命中时溅射",
      fn:function(p){p.projBurst=true}},
    {id:"e_fenmo",name:"分墨",type:"进化",tags:["远程"],effect:"大弹分裂为3颗小弹",
      fn:function(p){p.bigSplit=true}},
    {id:"e_suopo",name:"梭破",type:"进化",tags:["远程","暴击"],effect:"弹道随飞行距离增伤（最高+50%）",
      fn:function(p){p.projTravelDmg=true}},
    {id:"e_mojiao",name:"墨蛟",type:"进化",tags:["远程","暴击"],effect:"弹道体积+30%，暴击率+8%",
      fn:function(p){p.stats.projSize+=0.3;p.stats.critRate+=0.08}},
    {id:"e_shijian",name:"矢箭",type:"进化",tags:["远程","暴击"],effect:"弹速+30%，暴击伤害+25%",fn:function(p){p.stats.projSpd=(p.stats.projSpd||1)+0.3;p.stats.critDmg+=0.25}},
    {id:"e_moming",name:"墨冥",type:"进化",tags:["远程","击杀"],effect:"击杀后弹道分裂为3颗追踪弹",fn:function(p){p.killSplitProj=true}}
  ],
  aoe:[
    {id:"e_kuoyu",name:"扩域",type:"进化",tags:["控场"],effect:"范围+40%",
      fn:function(p){p.stats.range+=0.4}},
    {id:"e_gongming",name:"共鸣",type:"进化",tags:["控场"],effect:"多重+1",
      fn:function(p){p.stats.multi+=1}},
    {id:"e_zhenya",name:"镇压",type:"进化",tags:["控场"],effect:"声波命中减速3秒",
      fn:function(p){p.ringSlow=true}},
    {id:"e_shuangpin",name:"双频",type:"进化",tags:["控场"],effect:"第二圈不递减",
      fn:function(p){p.ringNoDecay=true}},
    {id:"e_huiming",name:"回鸣",type:"进化",tags:["控场","生存"],effect:"声波命中回复1HP",
      fn:function(p){p.ringHeal=true}},
    {id:"e_hunling",name:"魂灵",type:"进化",tags:["控场","魂"],effect:"攻击范围+25%，伤害+15%",
      fn:function(p){p.stats.range+=0.25;p.stats.dmg+=0.15}},
    {id:"e_jinggu",name:"惊鼓",type:"进化",tags:["控场","暴击"],effect:"范围+20%，暴击率+10%",fn:function(p){p.stats.range+=0.2;p.stats.critRate+=0.1}},
    {id:"e_zhenpo",name:"震魄",type:"进化",tags:["控场","击杀"],effect:"声波击杀触发范围恐惧",fn:function(p){p.ringKillFear=true}}
  ],
  dash:[
    {id:"e_jifeng",name:"疾风",type:"进化",tags:["突进"],effect:"移速+30%，伞击随速度增伤",
      fn:function(p){p.stats.spd+=0.3}},
    {id:"e_xuanren",name:"旋刃",type:"进化",tags:["突进"],effect:"多重+1，多段扫击",
      fn:function(p){p.stats.multi+=1}},
    {id:"e_tiebi",name:"铁壁",type:"进化",tags:["突进"],effect:"减伤+30%",
      fn:function(p){p.stats.def+=0.3}},
    {id:"e_kaihe",name:"开合",type:"进化",tags:["突进"],effect:"冲后反向补一刀",
      fn:function(p){p.dashReturn=true}},
    {id:"e_yingji",name:"影迹",type:"进化",tags:["突进","机动"],effect:"冲刺后留下墨迹减速敌人",
      fn:function(p){p.dashTrail=true}},
    {id:"e_huanying",name:"幻影",type:"进化",tags:["突进","机动"],effect:"移速+25%，闪避冷却-15%",
      fn:function(p){p.stats.spd+=0.25;p.stats.dodgeCd=(p.stats.dodgeCd||0)-0.15}},
    {id:"e_pinghuo",name:"平霍",type:"进化",tags:["突进","暴击"],effect:"伤害+30%，暴击率+8%",fn:function(p){p.stats.dmg+=0.3;p.stats.critRate+=0.08}},
    {id:"e_duanying",name:"断影",type:"进化",tags:["突进","机动"],effect:"闪避冷却-20%，移速+15%",fn:function(p){p.stats.dodgeCd=(p.stats.dodgeCd||0)-0.2;p.stats.spd+=0.15}},
    {id:"e_moying",name:"墨影",type:"进化",tags:["突进","击杀"],effect:"冲刺击杀刷新冲刺冷却",fn:function(p){p.dashKillReset=true}}
  ],
  summon:[
    {id:"e_zhaohun",name:"招魂",type:"进化",tags:["召物","法术"],effect:"幡的魂弹穿透敌人",
      fn:function(p){p.bannerPierce=true}},
    {id:"e_sanpo",name:"散魄",type:"进化",tags:["召物","暴击"],effect:"魂弹命中后爆裂伤害周围敌人",
      fn:function(p){p.bannerBurst=true}},
    {id:"e_lingjiang",name:"灵将",type:"进化",tags:["召物","击杀"],effect:"幡的攻击范围增大，魂弹伤害+40%",
      fn:function(p){p.bannerRangeBonus=80;p.bannerDmgMult=1.4}},
    {id:"e_lianfan",name:"连幡",type:"进化",tags:["召物","法术"],effect:"同时可存在两面幡",
      fn:function(p){p.bannerDouble=true}},
    {id:"e_guijiang",name:"归将",type:"进化",tags:["召物","生存"],effect:"幡附近持续回血",
      fn:function(p){p.bannerHeal=true}},
    {id:"e_youchong",name:"幽宠",type:"进化",tags:["召物","生存"],effect:"伤害+20%，防御+15%",
      fn:function(p){p.stats.dmg+=0.2;p.stats.def+=0.15}},
    {id:"e_youyu",name:"幽羽",type:"进化",tags:["召物","机动"],effect:"移速+20%，弹道体积+30%",fn:function(p){p.stats.spd+=0.2;p.stats.projSize+=0.3}},
    {id:"e_yousha",name:"幽杀",type:"进化",tags:["召物","暴击"],effect:"墨灵暴击率+20%，暴击时爆炸",fn:function(p){p.spiritCritBonus=(p.spiritCritBonus||0)+0.2;p.spiritExplode=true}}
  ]
};

var WAVES=[
  {label:"第壹波 · 纸门",mod:"calm",flavor:"纸门之后，邪祟初现。小心试探。",list:[{t:"zhikui",n:5}]},
  {label:"第贰波 · 纸灰巷",mod:"ash",flavor:"灰巷深处，纸灰迷目，游魂徘徊。",list:[{t:"zhikui",n:3},{t:"youhun",n:3},{t:"zhikuang",n:1}]},
  {label:"第叁波 · 悬井口",mod:"well",flavor:"井口之下引力难辨，焚灵与游魂交织。",list:[{t:"zhikui",n:3},{t:"youhun",n:3},{t:"fenling",n:2}],special:"survival"},
  {label:"第肆波 · 鬼灯廊",mod:"lantern",flavor:"鬼灯吐焰，分身鬼在暗处窥伺。",list:[{t:"youhun",n:2},{t:"gudeng",n:2},{t:"fenshen",n:2}],special:"horde"},
  {label:"第伍波 · 无面台",mod:"mask",flavor:"无面台上群邪毕至，食灰、僵客、墨盾齐出。",list:[{t:"zhikui",n:2},{t:"shigui",n:2},{t:"jiangshi",n:1},{t:"modun",n:1},{t:"fenshen",n:1}],special:"horde"},
  {label:"第陆波 · 鬼市",mod:"guishi",flavor:"鬼市幽灯，焚灵成群，食灰鬼挡道。",list:[{t:"shigui",n:3},{t:"fenling",n:3},{t:"gudeng",n:2},{t:"zhikuang",n:1}],special:"elite"},
  {label:"第柒波 · 墨池",mod:"inkpool",flavor:"墨池深处敌人暴虐。净化池水方为上策。",list:[{t:"jiangshi",n:2},{t:"youhun",n:3},{t:"gudeng",n:2},{t:"modun",n:2}],special:"survival"},
  {label:"第捌波 · 墨潮",mod:"inktide",flavor:"墨潮翻涌，全面围攻。这是最终考验。",list:[{t:"zhikui",n:3},{t:"shigui",n:2},{t:"jiangshi",n:2},{t:"fenshen",n:2},{t:"zhikuang",n:1},{t:"modun",n:1}]},
  {label:"镇守 · 画皮堂",mod:"lantern",flavor:"画皮娘子镇守此地。她有千面，你的刀只有一面。",list:[{t:"boss",n:1},{t:"gudeng",n:1},{t:"jiangshi",n:1},{t:"zhikuang",n:1},{t:"fenshen",n:2}]}
];

var STAGE_MODS={
  calm:{name:"净坛",desc:"无特殊地势，专心试武器。"},
  ash:{name:"纸灰风",desc:"灰圈会压低步速，击杀可吹散附近纸灰。"},
  well:{name:"悬井",desc:"井口周期牵引场上单位，走位会被打乱。"},
  mask:{name:"无面戏台",desc:"非首领初死会化作残影再起一次。"},
  lantern:{name:"鬼灯阵",desc:"鬼灯会间歇吐出阴火，击杀可让灯暂歇。"},
  inkpool:{name:"墨池",desc:"墨池中敌人攻击力+30%，击杀可净化为加速区。"},
  guishi:{name:"鬼市",desc:"地宫深处偶遇鬼市商贩，可用遗物换购。"},
  mirror:{name:"镜殿",desc:"敌人死亡时射出残影弹，保持移动避免被击中。"},
  inktide:{name:"墨潮",desc:"墨潮周期涌退，潮中敌人加速、玩家减速。"},
  moye:{name:"墨夜",desc:"全局视野缩小，击杀可短暂恢复视野。"},
  longmai:{name:"龙脉",desc:"地面出现龙脉能量线，沿线的敌人增伤30%，玩家沿线的攻击也增伤。"}
};

var ETYPE={
  zhikui:{name:"纸傀",tip:"近战小妖，数量多时注意走位",hp:45,spd:1.2,r:14,dmg:8,atkR:32,atkCd:48,col:C.ghost,edge:C.ghostE},
  youhun:{name:"游魂",tip:"远程弹射，注意闪避弹幕",hp:30,spd:1.6,r:12,dmg:6,atkR:260,atkCd:65,col:C.spirit,edge:C.moss,ranged:true,pSpd:4.5},
  fenling:{name:"焚灵",tip:"移动路径留下火场，保持距离",hp:55,spd:1.0,r:15,dmg:7,atkR:30,atkCd:50,col:C.fireG,edge:C.fire,fireTrail:true},
  shigui:{name:"食灰鬼",tip:"厚血近战，小心被围",hp:78,spd:0.85,r:17,dmg:10,atkR:34,atkCd:58,col:"rgba(141,125,105,0.45)",edge:C.ash},
  gudeng:{name:"骨灯",tip:"三方向弹射，走横向闪避",hp:42,spd:0.72,r:13,dmg:5,atkR:300,atkCd:82,col:C.goldG,edge:C.gold,ranged:true,pSpd:3.7,fanShot:3},
  jiangshi:{name:"僵客",tip:"会冲锋突进，看准蓄力时闪避",hp:88,spd:0.92,r:18,dmg:11,atkR:34,atkCd:58,col:"rgba(44,37,32,0.22)",edge:C.soft,charge:true,chargeCd:118,chargeSpeed:4.8},
  boss:{name:"画皮娘子",tip:"地宫之主，多阶段战斗",hp:320,spd:1.4,r:22,dmg:12,atkR:40,atkCd:40,col:C.bossG,edge:C.boss,isBoss:true,desperate:false},
  zhikuang:{name:"纸鸢匠",tip:"召唤小纸鸢，优先击杀",hp:52,spd:0.85,r:15,dmg:0,atkR:0,atkCd:120,col:C.goldG,edge:C.gold,
    summoner:true,summonCd:120,summonMax:4},
  fenshen:{name:"分身鬼",tip:"死后分裂为小鬼，准备追击",hp:65,spd:1.1,r:14,dmg:8,atkR:30,atkCd:50,col:"rgba(140,180,160,0.55)",edge:C.accent,
    splitter:true,splitCount:2,splitHpRatio:0.5},
  modun:{name:"墨盾鬼",tip:"自带墨盾，破盾后才有效伤害",hp:70,spd:0.8,r:16,dmg:9,atkR:32,atkCd:55,col:C.soft,edge:C.ink,
    hasShield:true,shield:30,maxShield:30,shieldRegen:300},
  mojiangjun:{name:"墨将军",tip:"古代镇墓将军，以墨为甲，以书为兵",hp:480,spd:0.8,r:28,dmg:15,atkR:45,atkCd:55,
    col:"rgba(23,19,16,0.55)",edge:C.ink,isBoss:true,desperate:false},
  moguiwang:{name:"墨鬼王",tip:"墨渊深处的古老存在，吞噬一切光明",hp:500,spd:0.75,r:30,dmg:18,atkR:50,atkCd:60,
    col:"rgba(23,19,16,0.6)",edge:C.accent,isBoss:true,desperate:false},
  moxian:{name:"墨仙",tip:"笔走龙蛇，以字为阵，以墨为法",hp:420,spd:1.0,r:26,dmg:14,atkR:180,atkCd:50,
    col:"rgba(70,90,80,0.45)",edge:C.moss,isBoss:true,desperate:false,ranged:true,pSpd:4},
  moya:{name:"墨鸦",tip:"飞行远程，快速且脆弱，优先点杀",hp:35,spd:1.9,r:11,dmg:5,atkR:240,atkCd:72,col:"rgba(23,19,16,0.35)",edge:C.ink,ranged:true,pSpd:5.2},
  shiyong:{name:"石俑",tip:"重甲盾兵，破盾后集火击杀",hp:95,spd:0.55,r:20,dmg:13,atkR:34,atkCd:68,col:"rgba(100,95,88,0.4)",edge:C.soft,hasShield:true,shield:28,maxShield:28,shieldRegen:360},
  yanyong:{name:"炎俑",tip:"重甲火径，走位时注意脚下",hp:95,spd:0.7,r:18,dmg:12,atkR:34,atkCd:62,col:"rgba(196,90,45,0.35)",edge:C.fire,fireTrail:true},
  sukui:{name:"速傀",tip:"极速近战，优先点杀",hp:38,spd:2.2,r:11,dmg:6,atkR:28,atkCd:32,col:"rgba(220,210,190,0.5)",edge:C.ash},
  duzhu:{name:"毒蛛",tip:"毒径减速，保持距离",hp:50,spd:1.6,r:13,dmg:8,atkR:30,atkCd:50,col:"rgba(77,97,86,0.45)",edge:C.moss,poisonTrail:true},
  gushi:{name:"蛊师",tip:"增益同伴，优先击杀",hp:65,spd:1.1,r:14,dmg:0,atkR:0,atkCd:0,col:"rgba(107,58,92,0.4)",edge:C.boss,summoner:false,buffAura:true},
  huapi:{name:"画皮",tip:"伪装成掉落物，靠近后突袭",hp:58,spd:2.1,r:13,dmg:12,atkR:30,atkCd:38,col:"rgba(196,90,45,0.3)",edge:C.accent,mimic:true},
  mozhi:{name:"墨蛭",tip:"近身吸附吸血，闪避可甩脱",hp:32,spd:2.5,r:8,dmg:0,atkR:0,atkCd:0,col:"rgba(23,19,16,0.4)",edge:C.ink,leech:true},
  motong:{name:"墨童",tip:"死后延迟爆炸，远离尸体",hp:28,spd:1.7,r:9,dmg:8,atkR:28,atkCd:42,col:"rgba(23,19,16,0.35)",edge:C.ink,deathBomb:true,deathBombR:60,deathBombDmg:12,deathBombDelay:55},
  mofu:{name:"墨蝠",tip:"高速俯冲撞击，优先点杀",hp:25,spd:3.2,r:9,dmg:10,atkR:60,atkCd:50,col:"rgba(23,19,16,0.3)",edge:C.ink,swoop:true,swoopPrep:35},
  modie:{name:"墨蝶",tip:"脆弱飞行，死后鼓舞附近敌人",hp:18,spd:2.8,r:8,dmg:6,atkR:200,atkCd:80,col:"rgba(77,97,86,0.35)",edge:C.moss,ranged:true,pSpd:4.8,deathBuff:true,deathBuffR:130,deathBuffT:180},
  moyong:{name:"墨蛹",tip:"死后孵化墨蚋，优先清除",hp:55,spd:1.2,r:12,dmg:0,atkR:0,atkCd:0,col:"rgba(60,55,50,0.4)",edge:C.ink,spawnsOnDeath:true,spawnType:"morui",spawnCount:2},
  morui:{name:"墨蚋",tip:"蛹体孵化，高速近战",hp:12,spd:3.6,r:5,dmg:5,atkR:22,atkCd:26,col:"rgba(23,19,16,0.3)",edge:C.accent},
  // v3.4 new enemies
  mozhu:{name:"墨蛛",tip:"远程吐丝减速，击杀后蛛网消散",hp:52,spd:1.4,r:13,dmg:7,atkR:220,atkCd:78,col:"rgba(60,55,50,0.4)",edge:C.moss,ranged:true,pSpd:4.0,webShot:true},
  mogu:{name:"墨骨",tip:"死后骨架重组一次，二次击杀才彻底",hp:72,spd:0.65,r:17,dmg:11,atkR:32,atkCd:60,col:"rgba(180,170,155,0.35)",edge:C.ash,reviveOnce:true,reviveHpRatio:0.4},
  momian:{name:"墨面",tip:"高速冲脸，被打前会蓄力",hp:42,spd:1.8,r:12,dmg:12,atkR:28,atkCd:44,col:"rgba(23,19,16,0.4)",edge:C.ink,swoop:true,swoopPrep:28},
  // v4.15 new enemy
  moying:{name:"墨萤",tip:"远程墨粉攻击，命中后短暂致盲降低玩家攻击范围",hp:38,spd:1.6,r:11,dmg:5,atkR:180,atkCd:65,col:"rgba(80,60,90,0.4)",edge:C.moss,ranged:true,pSpd:3.5,blindShot:true},
  // v4.12 new enemy
  mojar:{name:"墨罐",tip:"死后留下大范围减速墨迹，远离尸体",hp:55,spd:1.3,r:15,dmg:8,atkR:30,atkCd:55,col:"rgba(23,19,16,0.35)",edge:C.ink,deathSlow:true,deathSlowR:80,deathSlowT:120},
  mooushi:{name:"墨偶师",tip:"远程召唤师，边射墨弹边召唤傀儡",hp:55,spd:0.9,r:14,dmg:5,atkR:150,atkCd:70,col:"rgba(60,40,55,0.35)",edge:C.ghost,ranged:true,pSpd:3,summoner:true,summonCd:180,summonMax:3},
  mozhuhou:{name:"墨蛛后",tip:"会生成小蛛的精英型敌人，优先击杀",hp:85,spd:0.75,r:18,dmg:12,atkR:30,atkCd:50,col:"rgba(50,35,30,0.4)",edge:C.ink,summoner:true,summonCd:200,summonMax:4},
  // v4.25 new enemy
  moling:{name:"墨蛉",tip:"远程减速弹，中弹后行动迟缓",hp:48,spd:1.5,r:10,dmg:6,atkR:200,atkCd:72,col:"rgba(23,19,16,0.35)",edge:C.moss,ranged:true,pSpd:4.2,webShot:true},
  // v4.26 new enemy
  mobei:{name:"墨碑",tip:"带盾辅助型，死后增益周围敌人，先孤立再击杀",hp:82,spd:0.6,r:19,dmg:9,atkR:32,atkCd:65,col:"rgba(141,125,105,0.4)",edge:C.ash,
    hasShield:true,shield:32,maxShield:32,shieldRegen:340,
    deathBuff:true,deathBuffR:150,deathBuffT:220},
  // v4.27 new enemy
  mozhang:{name:"墨瘴",tip:"移动散布瘴气，死后释放墨潭减速，远程击杀为上",hp:62,spd:1.3,r:14,dmg:7,atkR:32,atkCd:54,col:"rgba(55,70,60,0.45)",edge:C.moss,
    poisonTrail:true,
    deathSlow:true,deathSlowR:85,deathSlowT:130},
  moyanshi:{name:"墨言师",tip:"远程施咒并召唤小鬼，优先击杀以阻止增援",hp:75,spd:0.7,r:14,dmg:8,atkR:220,atkCd:90,col:"rgba(120,80,160,0.9)",edge:C.spirit,
    ranged:true,pSpd:3,
    summoner:true,summonCd:300,summonMax:3,
    deathBomb:true,deathBombR:50,deathBombDmg:12,deathBombDelay:20},
  molizexi:{name:"墨裂蜥",tip:"冲锋后分裂为碎片，AOE速清",hp:28,spd:1.8,r:10,dmg:8,atkR:18,atkCd:80,
    col:"rgba(200,75,45,0.85)",edge:C.fire,
    charge:true,chargeCd:180,chargeSpeed:5,
    splitter:true,splitCount:3,splitHpRatio:0.25},
  // v6.0 new enemies
  moyinggui:{name:"墨影鬼",tip:"周期瞬移到玩家身后突袭，保持移动",hp:50,spd:1.6,r:12,dmg:10,atkR:30,atkCd:45,
    col:"rgba(60,50,70,0.35)",edge:C.ghost,teleport:true,teleportCd:180},
  moyishi:{name:"墨医师",tip:"周期治疗周围敌人，优先击杀阻止回血",hp:60,spd:0.9,r:14,dmg:0,atkR:0,atkCd:0,
    col:"rgba(90,138,74,0.4)",edge:C.moss,healAura:true,healAuraR:100,healAuraCd:150,healAuraAmt:8},
  // v6.2 new enemies
  moyingjiang:{name:"墨影将",tip:"重甲冲锋型，冲锋后短暂眩晕是输出窗口",hp:110,spd:0.7,r:20,dmg:14,atkR:34,atkCd:60,
    col:"rgba(50,40,55,0.5)",edge:C.ink,hasShield:true,shield:25,maxShield:25,shieldRegen:300,
    charge:true,chargeCd:140,chargeSpeed:5.5},
  moguchong:{name:"墨蛊虫",tip:"近身吸血并留毒径，闪避甩脱后远程击杀",hp:40,spd:2.3,r:9,dmg:0,atkR:0,atkCd:0,
    col:"rgba(70,90,60,0.4)",edge:C.moss,leech:true,poisonTrail:true},
  molingdeng:{name:"墨灵灯",tip:"远程灵弹，死后孵化小灯，群攻速清",hp:48,spd:0.8,r:12,dmg:6,atkR:220,atkCd:75,
    col:"rgba(140,120,80,0.5)",edge:C.gold,ranged:true,pSpd:3.5,
    spawnsOnDeath:true,spawnType:"modeng",spawnCount:2},
  // v9.0 new enemies x4
  molian:{name:"墨链电",tip:"链式电弧在敌人间跳跃，每次弹跳伤害+50%",hp:42,spd:1.3,r:12,dmg:5,atkR:180,atkCd:85,
    col:"rgba(80,140,200,0.5)",edge:C.frost,
    chainLightning:true,chainDmg:5,chainCount:3,chainRange:140},
  mohuanji:{name:"墨魂祭",tip:"击杀吸收祭品越战越强，保持火力压制",hp:60,spd:0.85,r:14,dmg:8,atkR:32,atkCd:55,
    col:"rgba(107,58,92,0.5)",edge:C.boss,
    soulHarvester:true},
  mofenshen:{name:"墨分身",tip:"HP低于50%时分裂为两个低血分身，优先集火",hp:88,spd:1.1,r:14,dmg:9,atkR:30,atkCd:50,
    col:"rgba(140,180,160,0.45)",edge:C.accent,
    cloneOnHalf:true,cloneHpRatio:0.35},
  moshizhe:{name:"墨噬者",tip:"击杀回血，被围更危险，保持距离用AOE清理",hp:75,spd:1.0,r:15,dmg:10,atkR:32,atkCd:52,
    col:"rgba(44,37,32,0.5)",edge:C.ink,
    vampiric:true,vampiricHeal:15},
  // v13.0 new enemies
  mobi:{name:"墨笔",tip:"远程追踪墨线，被缠住减速，保持走位",hp:55,spd:1.4,r:11,dmg:7,atkR:200,atkCd:80,
    col:"rgba(100,80,60,0.45)",edge:C.ink,ranged:true,pSpd:3.8,webShot:true},
  moyao:{name:"墨妖",tip:"击杀后自爆大范围墨潭，远程击杀后远离",hp:70,spd:1.2,r:16,dmg:9,atkR:34,atkCd:50,
    col:"rgba(163,58,45,0.4)",edge:C.accent,
    deathBomb:true,deathBombR:70,deathBombDmg:15,deathBombDelay:25,
    deathSlow:true,deathSlowR:90,deathSlowT:140},
  mofeng:{name:"墨蜂",tip:"极速飞行群体，低血高伤，AOE速清",hp:28,spd:2.8,r:8,dmg:10,atkR:22,atkCd:30,
    col:"rgba(200,160,40,0.5)",edge:C.gold}
};
// spawnType target
ETYPE.modeng={name:"墨灯",tip:"灵灯孵化物，快速近战",hp:15,spd:2.8,r:6,dmg:5,atkR:22,atkCd:30,
  col:"rgba(180,160,100,0.4)",edge:C.gold};

var LIMITS={particles:260,fires:72,attacks:90,eProj:90,floatTexts:18,decoys:12,kites:4,frosts:12,enemies:80,inkSpirits:6};

var PREREQS={
  huosui:function(s){return !!s.ownedIds.yedeng},
  fanzhao:function(s){return s.stats.returnInk>0},
  lingmu:function(s){return s.slowOnHit>0||s.ringSlow},
  liuying:function(s){return s.weaponType==="dash"},
  pojing:function(s){return s.weaponType==="dash"},
  fengma:function(s){return s.weaponType==="dash"},
  hunqian:function(s){return !!(s.ownedIds.dieyin||(s.ownedIds.lingmu&&(s.slowOnHit>0||s.ringSlow)))},
  zhupi:function(s){return !!s.ownedIds.tongjing},
  xueqi:function(s){return s.weaponType==="melee"},
  dengxin:function(s){return !!s.ownedIds.yedeng},
  mogangyin:function(s){return !!(s.ownedIds.judou||s.ownedIds.mojiaojin)},
  lianhuanfu:function(s){return !!s.ownedIds.dieyin},
  yanmoyan:function(s){return !!s.ownedIds.yedeng},
  binghe:function(s){return !!s.ownedIds.liebing},
  houmo:function(s){return s.stats.projSize>1.2},
  molonglin:function(s){return !!s.ownedIds.shixin},
  molingqi:function(s){return !!s.ownedIds.molingyu},
  zhenyan:function(s){return !!(s.ownedIds.moshouzhen||s.ownedIds.mogongzhen)},
  huichunzhen:function(s){return !!(s.ownedIds.moshouzhen||s.ownedIds.mogongzhen)},
  mobao:function(s){return !!(s.ownedIds.moshouzhen||s.ownedIds.mogongzhen||s.ownedIds.huichunzhen||s.ownedIds.mowo)},
  moxian:function(s){return !!((s.ownedIds.moshouzhen?1:0)+(s.ownedIds.mogongzhen?1:0)+(s.ownedIds.huichunzhen?1:0)+(s.ownedIds.mowo?1:0)+(s.ownedIds.mobao?1:0)>=2)},
  moding:function(s){return s.weaponType==="melee"},
  mochen:function(s){return !!(s.ownedIds.moshouzhen||s.ownedIds.mogongzhen||s.ownedIds.huichunzhen||s.ownedIds.mowo)},
  moyi:function(s){return s.weaponType==="dash"},
  moshi:function(s){return !!s.ownedIds.molian},
  monu:function(s){return !!s.ownedIds.tongjing},
  baomo:function(s){return !!s.ownedIds.molingyu},
  yumo:function(s){return !!s.ownedIds.molingyu},
  hanmo:function(s){return !!s.ownedIds.molingyu},
  fengmofu:function(s){return s.slowOnHit>0||s.ringSlow},
  hunfanling:function(s){return s.weaponType==="summon"},
  xianluowen:function(s){return s.weaponType==="aoe"||s.weaponType==="summon"},
  moduanren:function(s){return s.weaponType==="melee"},
  moxuejian:function(s){return s.weaponType==="melee"},
  moguidan:function(s){return s.weaponType==="ranged"},
  mosheying:function(s){return s.weaponType==="ranged"},
  mohunyin:function(s){return s.weaponType==="aoe"},
  mozhenling:function(s){return s.weaponType==="aoe"},
  moyingshan:function(s){return s.weaponType==="dash"},
  mopofeng:function(s){return s.weaponType==="dash"},
  mohunzhui:function(s){return s.weaponType==="summon"},
  molianhun:function(s){return s.weaponType==="summon"},
  mozhuiyu:function(s){return !!s.ownedIds.mochuanshe},
  mopianxing:function(s){return !!s.ownedIds.mochuanshe}
};

var CAPS={critRate:0.65,bellCombo:15,shieldStack:3,atkCdFloor:4,soulChain:4,ringSoul:6,projSize:2.0,defMax:0.6};

var RANGES={weakSpread:100,fireExpand:60,fear:100,soulChain:80,burst:50,
  decoyAttract:120,chargeMax:240,chargeMin:54,rangedMin:50,
  killPulse:100,critShrapnel:80,dodgeSoulGrab:120,inkSpirit:220,
  spiritExplode:60,swoop:180,mimicReveal:55,buffAura:90,split:120,retaliate:80,splashBoom:55};

var TUNING={
  comboWindow:45,chargeThreshold:50,
  playerSpd:3.4,playerHp:100,playerR:15,
  dodgeDuration:10,dodgeCooldown:36,dodgeInvFrames:16,justDodgedWindow:28,
  hurtInvFrames:30,lowHpThreshold:0.3,bossEnrageHp:0.5,bossDesperateHp:0.25,
  bossEnrageSpdMult:1.3,reviveHpRatio:0.3,
  fastAtkCdMult:0.55,fastAtkParticleMult:0.5,
  combo3Arc:1.4,combo3Range:1.25,combo3Dmg:1.25,
  shieldStackReduction:4,inkPoolDmgMult:1.3,
  killStreak5Dmg:1.1,killStreak10Dmg:1.2,
  eliteBaseChance:0.1,eliteWaveScale:0.025,eliteMaxChance:0.4,eliteHardBonus:0.08,eliteNightmareBonus:0.18,elitePurgatoryBonus:0.3,
  defFormReduction:0.75,formDefReduction:0.85,
  bossChargeSpd:5.5,bossChargeDur:14,bossPrepDur:20,
  perfThreshFull:0.95,perfThreshHigh:0.85,perfThreshMed:0.72,perfThreshLow:0.55,
  perfMulFull:0.25,perfMulHigh:0.4,perfMulMed:0.6,perfMulLow:0.8,
  killStreakWindow:120,speedBurstDuration:180,spawnGraceDuration:30,deathAnimDuration:18,
  buffedSpdMult:1.3,defaultSlowAmount:0.3,fireTickInterval:20,
  survivalMaxEnemies:20,survivalSpawnBase:90,survivalSpawnJitter:60,
  killSpeedBonus:0.25,speedBurstBonus:0.2,lowHpFuryBonus:0.15,lowHpFuryThreshold:0.5,
  eliteHpMult:1.5,eliteSpdMult:1.3,eliteArmoredSpdMult:0.7,
  reviveInvFrames:60,
  lowHpFuryDmgMult:1.25,lowHpRangeThreshold:0.35,lowHpRangeMult:1.4,
  killBoostDmgMult:1.45,
  bossChargeRange:200,bossNormalAtkInterval:140,
  bossPhase2Hp:0.6,bossPhase3Hp:0.25,
  eProjWarnMin:120,eProjWarnMax:280
};

var DEATH_COLOR={zhikui:"ash",youhun:"moss",fenling:"fire",shigui:"soft",gudeng:"gold",jiangshi:"ink",boss:"accent",
  zhikuang:"ghost",fenshen:"soul",modun:"soft",mojiangjun:"ink",moguiwang:"accent",moya:"ink",shiyong:"soft",yanyong:"fire",sukui:"ash",duzhu:"moss",gushi:"accent",huapi:"accent",mozhi:"ink",motong:"ink",mofu:"ink",modie:"moss",moyong:"ink",morui:"accent",mozhu:"moss",mogu:"ash",momian:"ink",mojar:"ink",moying:"moss",mooushi:"ghost",mozhuhou:"ink",moling:"moss",mobei:"ash",mozhang:"moss",moyanshi:"soul",molizexi:"fire",moyinggui:"ghost",moyishi:"moss",moyingjiang:"ink",moguchong:"moss",molingdeng:"gold",modeng:"gold"};

var JUDGMENTS=["斩业已断","纸命归灰","照见真形","朱批落定","一念归尘","墨尽灯枯","形消魄散","笔落惊魂"];

var PCOL={ink:C.ink,accent:C.accent,moss:C.moss,soul:"rgba(100,140,120,0.8)",fire:C.fire,ash:C.ash,soft:C.soft,gold:C.gold,ghost:C.ghost};

var BUILD_PREFS={
  melee:["近战","处决","暴击","击杀","生存","魂","防御","溅射","爆炸","生命","攻速"],
  ranged:["远程","法术","分裂","魂","暴击","击杀","召物","攻速","溅射","持续"],
  aoe:["控场","召物","魂","冰","暴击","击杀","爆发","爆炸","持续","诅咒","范围","减益"],
  dash:["闪避","反击","机动","远程","火","击杀","生存","防御","治疗","生命","冲刺"],
  summon:["召物","法术","魂","击杀","生存","火","爆发","治疗","持续","生命","诅咒","召唤","减益"]
};

// --- Procedural wave generation helpers ---
function _ri(a,b){return Math.floor(a+Math.random()*(b-a+1))}
function _pick(a){return a[Math.floor(Math.random()*a.length)]}
// --- Procedural wave generation ---
var ENEMY_COST={zhikui:1,youhun:1.5,zhikuang:1.5,fenling:2,gudeng:2,shigui:2.5,fenshen:2.5,modun:2.5,jiangshi:3,moya:1.8,shiyong:3,yanyong:2.2,sukui:1.3,duzhu:1.7,gushi:2.8,huapi:1.9,mozhi:1.4,motong:1.2,mofu:1.1,modie:1.5,moyong:2.0,morui:0.7,mozhu:1.8,mogu:2.8,momian:1.6,mojar:2.0,moying:1.5,mooushi:2.5,mozhuhou:3.0,moling:1.8,mobei:2.5,mozhang:2.0,moyanshi:2.3,molizexi:1.9,moyinggui:2.2,moyishi:2.5,moyingjiang:3.5,moguchong:1.6,molingdeng:2.0,modeng:0.6,boss:99,mojiangjun:99,moguiwang:99,moxian:99,mobi:2.0,moyao:2.5,mofeng:1.5};
var WAVE_BUDGETS=[5,7,9.5,12,14.5,17.5,21,25,28,32,36,0];
var WAVE_TIERS=[
  ["zhikui","youhun"],
  ["zhikui","youhun","fenling","zhikuang","moya","sukui","huapi","mozhi","motong","mofu","modie","morui","moying","molizexi"],
  ["zhikui","youhun","fenling","gudeng","shigui","fenshen","moya","shiyong","sukui","yanyong","duzhu","morui","moyong","mozhu","moying","mooushi","moling","mozhang","moyanshi"],
  ["zhikuang","fenling","gudeng","shigui","fenshen","modun","jiangshi","moya","shiyong","yanyong","gushi","moyong","mozhu","mogu","mojar","mooushi","mobei","moyanshi","moyinggui","molingdeng"],
  ["fenling","gudeng","shigui","fenshen","modun","jiangshi","moya","shiyong","yanyong","duzhu","gushi","mozhu","mogu","momian","mojar","mooushi","mozhuhou","moyinggui","moyishi","moyingjiang","moguchong"]
];
var WAVE_PLACES=["纸门","纸灰巷","悬井口","鬼灯廊","无面台","墨池","灰潮","百鬼面","黄泉路","枯骨桥","阴风道","鬼市","鸦栖楼","幽冥渡"];
var WAVE_FLAVORS=["此处邪祟暗藏，小心试探。","前方鬼影绰绰，不可大意。","阴气渐重，步步为营。","群邪毕至，殊死一搏。","地宫深处，杀机四伏。"];
var STAGE_POOLS=[
  ["calm"],
  ["calm","ash"],
  ["ash","well","lantern"],
  ["ash","well","lantern","mask","inkpool","mirror","guishi","inktide"],
  ["mask","inkpool","mirror","lantern","inktide"]
];
var CN_NUM=["壹","贰","叁","肆","伍","陆","柒","捌","玖","拾","拾壹","拾贰"];

function generateWave(wi,diff){
  if(wi>=WAVE_BUDGETS.length||WAVE_BUDGETS[wi]===0)return null; // boss wave handled separately
  var tier=Math.min(4,Math.floor(wi/2));
  var pool=WAVE_TIERS[tier];
  var diffMul=diff==="hard"?1.15:diff==="nightmare"?1.35:diff==="purgatory"?1.55:1;
  var budget=WAVE_BUDGETS[wi]*diffMul;
  var list=[];
  var totalCost=0;
  var expensive={jiangshi:0,modun:0,fenshen:0,shiyong:0,shigui:0};

  // Special wave types (after wave 1, ~20% chance)
  var specialWave=null;
  if(wi>=2&&Math.random()<0.2){
    var specials=["horde","elite","survival"];
    if(diff==="nightmare")specials.push("elite_horde");
    if(diff==="purgatory"){specials.push("elite_horde");specials.push("elite");}
    specialWave=_pick(specials);
    if(specialWave==="horde"){budget*=1.7;}
    else if(specialWave==="elite_horde"){budget*=1.4;}
    else if(specialWave==="elite"){budget*=0.8;}
    else if(specialWave==="survival"){budget*=1.3;}
  }

  for(var attempt=0;attempt<40&&totalCost<budget*0.9;attempt++){
    var t=_pick(pool);
    var c=ENEMY_COST[t]||1;
    if(totalCost+c>budget*1.1)continue;
    if(expensive[t]>=2)continue;
    var found=false;
    for(var j=0;j<list.length;j++){if(list[j].t===t){list[j].n++;found=true;break}}
    if(!found)list.push({t:t,n:1});
    totalCost+=c;
    if(expensive[t]!==undefined)expensive[t]++;
  }
  var total=0;list.forEach(function(e){total+=e.n});
  if(total<3){list.push({t:"zhikui",n:3-total})}
  while(total>18){var biggest=list.reduce(function(a,b){return a.n>b.n?a:b});biggest.n--;total--}
  var sp=STAGE_POOLS[tier];
  var mod=sp[wi%sp.length];
  return{label:"第"+CN_NUM[wi]+"波 · "+WAVE_PLACES[_ri(0,WAVE_PLACES.length-1)],
    mod:mod,flavor:_pick(WAVE_FLAVORS),list:list,special:specialWave};
}

// --- Curse/Oath system (誓印) ---
var CURSES=[
  {id:"mobu",name:"墨缚",type:"誓印",tags:["近战","法术"],
    desc:"无法闪避，但伤害+35%，攻击范围+20%",
    fn:function(p){p.noDodge=true;p.stats.dmg+=0.35;p.stats.range+=0.2}},
  {id:"shihun",name:"噬魂",type:"誓印",tags:["生存","诅咒"],
    desc:"波次间不回血，但遗物效果增强50%",
    fn:function(p){p.noWaveHeal=true;p.relicPower=1.8}},
  {id:"zhibao",name:"纸薄",type:"誓印",tags:["生存","暴击"],
    desc:"最大生命降至60，但开局多选2件遗物",
    fn:function(p){p.maxHpOverride=60;p.extraStartRelics=2}},
  {id:"tanmo",name:"贪墨",type:"誓印",tags:["击杀","诅咒"],
    desc:"敌人生命+40%，但每波多选1件遗物",
    fn:function(p){p.enemyHpMult=1.4;p.extraRelicChoice=true}},
  {id:"guxing",name:"孤行",type:"誓印",tags:["法术","暴击"],
    desc:"没有武器进化，但全属性+30%，攻速提升",
    fn:function(p){p.noEvolution=true;p.stats.dmg+=0.3;p.stats.spd+=0.3;p.stats.range+=0.3;p.stats.atkSpd-=0.12}},
  {id:"guijianchou",name:"鬼见愁",type:"誓印",tags:["暴击","处决"],
    desc:"所有敌人皆煞化，但暴击率+25%",
    fn:function(p){p.allElite=true;p.stats.critRate=Math.min(CAPS.critRate,p.stats.critRate+0.25)}},
  {id:"kuangxue",name:"狂血",type:"誓印",tags:["近战","暴击"],
    desc:"无法闪避，但暴击伤害+60%",
    fn:function(p){p.noDodge=true;p.stats.critDmg+=0.6}},
  {id:"moyin",name:"墨瘾",type:"誓印",tags:["法术","诅咒"],
    desc:"伤害+30%，但波次间不回血",
    fn:function(p){p.stats.dmg+=0.3;p.noWaveHeal=true}},
  {id:"miwu",name:"迷雾",type:"誓印",tags:["生存","诅咒"],
    desc:"周期性视野缩小，但移速+40%",
    fn:function(p){p.fogCurse=true;p.stats.spd+=0.4}},
  {id:"guihuo",name:"鬼火",type:"誓印",tags:["法术","诅咒"],
    desc:"敌人死亡产生追踪魂球，但击杀回血+8",
    fn:function(p){p.soulOrbCurse=true;p.killHeal=(p.killHeal||0)+8}},
  {id:"lingshi",name:"灵噬",type:"誓印",tags:["召物","诅咒"],
    desc:"墨灵伤害翻倍，但每波开始每只墨灵扣除2点生命",
    fn:function(p){p.spiritDmgBonus=(p.spiritDmgBonus||0)+1.0;p.spiritHpCost=true}},
  {id:"mojie",name:"墨竭",type:"誓印",tags:["生存","诅咒"],
    desc:"墨阵效果翻倍，但最大生命-25%",
    fn:function(p){p.formDouble=true;p.maxHpOverride=75}},
  {id:"moqi",name:"墨契",type:"誓印",tags:["暴击","生存"],
    desc:"攻击范围-30%，但每次暴击回复3点生命",
    fn:function(p){p.stats.range-=0.3;p.critHeal=true}},


  {id:"kuangmo",name:"狂墨",type:"誓印",tags:["攻速","诅咒"],
    desc:"攻速+30%，每次攻击消耗1HP，但击杀回复8HP",
    fn:function(p){p.stats.atkSpd-=0.18;p.atkHpCost=true;p.killHeal=(p.killHeal||0)+8}},
  // v3.4 new curses
  {id:"xushi",name:"虚实",type:"誓印",tags:["生存","暴击"],
    desc:"敌人周期隐身，但暴击伤害+50%",
    fn:function(p){p.enemyFlicker=true;p.stats.critDmg+=0.5}},
  {id:"moyin_brand",name:"墨印",type:"誓印",tags:["生存","遗物"],
    desc:"追踪墨球威胁你，但开局多2件遗物",
    fn:function(p){p.inkBrandCurse=true;p.extraStartRelics=(p.extraStartRelics||0)+2}},
  {id:"jinghua",name:"镜花",type:"誓印",tags:["法术","诅咒"],
    desc:"攻击20%几率落空，但命中时伤害x1.8",
    fn:function(p){p.missChance=0.2;p.hitDmgMult=1.8}},
  // v4.3 new curses
  {id:"anchao",name:"暗潮",type:"誓印",tags:["生存","诅咒"],
    desc:"敌人移速+30%，但击杀回复5HP",
    fn:function(p){p.enemySpdMult=1.3;p.killHeal=(p.killHeal||0)+5}},
  {id:"mofeng",name:"墨封",type:"誓印",tags:["遗物","诅咒"],
    desc:"遗物上限降至3件，但伤害+50%",
    fn:function(p){p.maxRelicsOverride=3;p.stats.dmg+=0.5}},
  {id:"moxuan",name:"墨旋",type:"誓印",tags:["机动","法术"],
    desc:"移动留下减速墨迹，但静止时受伤+30%",
    fn:function(p){p.moveSlowTrail=true;p.stillDmgMult=1.3}},
  // v4.16 new curse
  {id:"moxue",name:"墨血",type:"誓印",tags:["近战","暴击"],
    desc:"连击越高伤害越高(每层+8%)，但受伤也随连击增加(每层+5%)",
    fn:function(p){p.comboDmgScale=true;p.comboVuln=true}},
  {id:"mosuo",name:"墨锁",type:"誓印",tags:["召物","诅咒"],
    desc:"墨灵上限+2但每只墨灵使最大生命-10",
    fn:function(p){p.inkSpiritCount=(p.inkSpiritCount||0)+2;p.hasInkSpirit=true;p.spiritHpPenalty=(p.spiritHpPenalty||0)+10}},
  // v6.2 new curses
  {id:"saiweng",name:"塞翁失马",type:"誓印",tags:["生存","治疗"],
    desc:"最大生命-30%，但每波结束回复30%最大生命",
    fn:function(p){p.maxHpMult=0.7;p.waveEndHeal=true;p.waveEndHealRatio=0.3}},
  {id:"yixue",name:"以血换血",type:"誓印",tags:["暴击","诅咒"],
    desc:"攻击力+40%，受伤+30%",
    fn:function(p){p.stats.dmg+=0.4;p.dmgTakenMult=(p.dmgTakenMult||1)+0.3}},
  {id:"guzhu",name:"孤注一掷",type:"誓印",tags:["遗物","诅咒"],
    desc:"遗物上限降至3件，但每件遗物效果+50%",
    fn:function(p){p.maxRelicsOverride=3;p.relicPower=1.5}},
  // v9.0 新誓印 x3
  {id:"huwei",name:"虎卫",type:"誓印",tags:["生存","近战"],
    desc:"受伤时有30%概率闪避，但伤害-15%",
    fn:function(p){p.dodgeOnHurt=true;p.stats.dmg-=0.15}},
  {id:"canglang",name:"沧浪",type:"誓印",tags:["法术","生存"],
    desc:"生命值越低，伤害越高(最低+60%)，但移速-20%",
    fn:function(p){p.lowDmgBoost=true;p.stats.spd-=0.2}},
  {id:"qianniao",name:"潜鸟",type:"誓印",tags:["机动","诅咒"],
    desc:"击杀后移速+10%持续5秒(可叠加)，但攻击范围-25%",
    fn:function(p){p.killSpeed=true;p.stats.range-=0.25}},
  // v13.0 新誓印 x3
  {id:"moyu",name:"墨羽",type:"誓印",tags:["机动","法术"],
    desc:"移速+50%，但攻击冷却+20%",
    fn:function(p){p.stats.spd+=0.5;p.stats.atkSpd+=0.2}},
  {id:"xuehun",name:"血魂",type:"誓印",tags:["暴击","诅咒"],
    desc:"暴击伤害+80%，但最大生命-40%",
    fn:function(p){p.stats.critDmg+=0.8;p.maxHpOverride=60}},
  {id:"fumo",name:"伏墨",type:"誓印",tags:["法术","击杀"],
    desc:"每击杀15个敌人获得1件随机遗物，但波次间不回血",
    fn:function(p){p.killRelicEvery15=true;p.noWaveHeal=true}}
];
// --- Stage Hazards (random per wave) ---
var STAGE_HAZARDS=[
  {id:"yinfeng",name:"阴风",desc:"随机方向推力影响所有单位",interval:180},
  {id:"moyu",name:"墨雨",desc:"随机掉落墨点，接触扣血",interval:45},
  {id:"guihuoyan",name:"鬼火焰",desc:"随机出现追踪火球",interval:120},
  {id:"mozhang",name:"墨瘴",desc:"毒瘴缓缓飘移，穿越造成持续伤害",interval:200},
  {id:"yinbing",name:"阴兵借道",desc:"一排幽灵骑兵横穿战场",interval:210},
  {id:"zhijian",name:"纸剑雨",desc:"纸剑从上方坠落",interval:80},
  // v9.0 新关卡调制器 x2
  {id:"moluo",name:"墨落",desc:"墨滴从天空缓慢滴落，接触造成减速",interval:60},
  {id:"guiying",name:"鬼影",desc:"随机阴影在地面游走，接触造成恐惧",interval:150}
];

// --- Achievements / Meta-progression ---
var ACHIEVEMENTS=[
  {id:"first_run",name:"初入地宫",desc:"完成一次走阴",check:function(m){return m.totalRuns>=1},reward:null},
  {id:"win_jian",name:"剑斩祟",desc:"用斩妖剑通关",check:function(m){return (m.weaponsCleared.jian||0)>0},reward:null},
  {id:"win_bi",name:"笔诛邪",desc:"用符骨笔通关",check:function(m){return (m.weaponsCleared.bi||0)>0},reward:null},
  {id:"win_ling",name:"铃镇煞",desc:"用镇魂铃通关",check:function(m){return (m.weaponsCleared.ling||0)>0},reward:null},
  {id:"win_san",name:"伞伏魔",desc:"用伏魔伞通关",check:function(m){return (m.weaponsCleared.san||0)>0},reward:null},
  {id:"win_fan",name:"幡招魂",desc:"用召魂幡通关",check:function(m){return (m.weaponsCleared.fan||0)>0},reward:null},
  {id:"all_weapons",name:"法器皆通",desc:"用全部武器通关",check:function(m){
    return["jian","bi","ling","san","fan"].every(function(w){return(m.weaponsCleared[w]||0)>0})},reward:"startRelic"},
  {id:"kill_mojiangjun",name:"墨将军克星",desc:"击杀墨将军",check:function(m){return m.mojiangjunKills>0},reward:"goldInk"},
  {id:"relic_20",name:"遗物学徒",desc:"发现20件遗物",check:function(m){return Object.keys(m.relicsDiscovered).length>=20},reward:null},
  {id:"relic_30",name:"遗物大师",desc:"发现30件遗物",check:function(m){return Object.keys(m.relicsDiscovered).length>=30},reward:"startRelic"},
  {id:"kills_1000",name:"千斩",desc:"累计斩杀一千祟",check:function(m){return m.totalKills>=1000},reward:null},
  {id:"runs_10",name:"走阴老手",desc:"完成十次走阴",check:function(m){return m.totalRuns>=10},reward:null},
  {id:"nightmare_win",name:"噩梦行者",desc:"噩梦难度通关",check:function(m){return m.nightmareWins>0},reward:"startRelic"},
  {id:"purgatory_win",name:"炼狱行者",desc:"炼狱难度通关",check:function(m){return (m.purgatoryWins||0)>0},reward:"startRelic"},
  {id:"hard_win",name:"险途征服",desc:"险途难度通关",check:function(m){return (m.hardWins||0)>0},reward:null},
  {id:"kill_huapi",name:"画皮克星",desc:"击败画皮娘子",check:function(m){return (m.bossKills||0)>0},reward:null},
  {id:"grade_S",name:"墨上墨",desc:"获得S级评价",check:function(m){return m.bestGrade==="S"},reward:null},
  {id:"boss_kills_5",name:"镇祟者",desc:"击杀5个Boss",check:function(m){return m.bossKills>=5},reward:null},
  {id:"curse_master",name:"誓印皆立",desc:"使用过全部誓印",check:function(m){return Object.keys(m.cursesUsed||{}).length>=CURSES.length},reward:null},
  {id:"elite_hunter",name:"精英猎手",desc:"累计击杀50个精英敌人",check:function(m){return (m.eliteKills||0)>=50},reward:null},
  {id:"relic_35",name:"遗物学者",desc:"发现35件遗物",check:function(m){return Object.keys(m.relicsDiscovered).length>=35},reward:"startRelic"},
  {id:"fire_kills",name:"火中取栗",desc:"单局用火焰击杀10个敌人",check:function(m){return (m.bestFireKills||0)>=10},reward:null},
  // --- Easter egg achievements ---
  {id:"no_move_win",name:"不动如山",desc:"全程不按WASD通关（闪避移动不算）",check:function(m){return (m.noMoveWins||0)>0},reward:null},
  {id:"low_hurt_win",name:"一刀不漏",desc:"受伤不超过3次通关",check:function(m){return (m.lowHurtWins||0)>0},reward:null},
  {id:"speed_clear",name:"暴走夜行",desc:"单波30秒内清场",check:function(m){return (m.fastWaveClears||0)>=1},reward:null},
  {id:"paper_win",name:"纸糊的人",desc:"纸薄誓印通关",check:function(m){return (m.paperWins||0)>0},reward:null},
  {id:"no_relic_win",name:"赤手空拳",desc:"不拾取任何遗物通关",check:function(m){return (m.noRelicWins||0)>0},reward:null},
  {id:"massacre",name:"百鬼夜行",desc:"单局击杀100+敌人",check:function(m){return (m.bestSingleRunKills||0)>=100},reward:null},
  {id:"perfect_boss",name:"完美谢幕",desc:"Boss战不受伤",check:function(m){return (m.perfectBossKills||0)>0},reward:null},
  {id:"no_evolve_win",name:"孤勇者",desc:"孤行誓印通关",check:function(m){return (m.noEvolveWins||0)>0},reward:null},
  {id:"kill_moguiwang",name:"墨鬼王克星",desc:"击败墨鬼王",check:function(m){return (m.moguiwangKills||0)>0},reward:null},
  {id:"kill_moxian",name:"墨仙克星",desc:"击败墨仙",check:function(m){return (m.moxianKills||0)>0},reward:null},
  {id:"quad_boss",name:"四祟尽灭",desc:"击败过全部四个Boss",check:function(m){return (m.bossKills||0)>=1&&(m.mojiangjunKills||0)>=1&&(m.moguiwangKills||0)>=1&&(m.moxianKills||0)>=1},reward:"goldInk"},
  {id:"max_relics",name:"六器加身",desc:"单局集满6件遗物",check:function(m){return (m.maxRelicsInRun||0)>=6},reward:null},
	  {id:"ash_road",name:"灰烬之路",desc:"单局战斗结束时磷火覆盖过半场",check:function(m){return (m.bestFireCoverage||0)>=0.5},reward:"goldInk"},
  {id:"swift_step",name:"疾风步",desc:"单局墨迹残步充能释放10次以上",check:function(m){return (m.bestMoveChargeFires||0)>=10},reward:null},
  {id:"chain_reaction",name:"连锁墨爆",desc:"墨爆印单局爆炸击杀10个以上敌人",check:function(m){return (m.bestKillExplodeKills||0)>=10},reward:null},
  {id:"blind_fight",name:"盲斗",desc:"致盲状态下累计击杀10个敌人",check:function(m){return (m.bestBlindKills||0)>=10},reward:null},
  {id:"bone_life",name:"百骨长生",desc:"骨续泉单局累计回复20点以上生命",check:function(m){return (m.bestWaveHpHealed||0)>=20},reward:null},
  {id:"last_stand",name:"绝地逢生",desc:"墨魂丹低血爆发状态下击杀20个敌人",check:function(m){return (m.bestLowHpBurstKills||0)>=20},reward:null},
  {id:"spider_slayer",name:"蛛后克星",desc:"单局击杀3只墨蛛后",check:function(m){return (m.mozhuhouKills||0)>=3},reward:null},
  {id:"chain_execute",name:"墨爆连环",desc:"单局通过墨爆弹引爆击杀15个敌人",
    check:function(m){return (m.bestExecuteKills||0)>=15},reward:null},
  {id:"combo_20",name:"连斩达人",desc:"单局最高连斩达到20",check:function(m){return (m.bestCombo||0)>=20},reward:null},
  {id:"dodge_master",name:"闪避大师",desc:"单局闪避次数达到30",check:function(m){return (m.bestDodgeKills||0)>=30},reward:null},
  // v9.0 新成就 x5
  {id:"combo_30",name:"连斩宗师",desc:"单局最高连斩达到30",check:function(m){return (m.bestCombo||0)>=30},reward:null},
  {id:"crit_50",name:"暴击如雨",desc:"单局暴击击杀50个敌人",check:function(m){return (m.critKills||0)>=50},reward:null},
  {id:"elite_20",name:"精英杀手",desc:"单局击杀20个精英敌人",check:function(m){return (m.eliteKills||0)>=20},reward:null},
  {id:"survival_master",name:"绝境逢生",desc:"生存波击杀数量超过敌人总数150%",check:function(m){return (m.survivalMaster||0)>=1},reward:null},
  {id:"relic_50",name:"遗物猎人",desc:"单局见过50件不同遗物",check:function(m){return (m.relicsSeen||0)>=50},reward:null},
  // v11.0 无尽模式成就
  {id:"endless_15",name:"无尽初探",desc:"无尽模式到达15波",check:function(m){return (m.bestEndlessWave||0)>=15},reward:null},
  {id:"endless_25",name:"无尽踏行",desc:"无尽模式到达25波",check:function(m){return (m.bestEndlessWave||0)>=25},reward:"startRelic"},
  {id:"endless_50",name:"无尽深渊",desc:"无尽模式到达50波",check:function(m){return (m.bestEndlessWave||0)>=50},reward:"goldInk"},
  {id:"daily_3",name:"三朝走阴",desc:"连续3天完成每日种子挑战",check:function(m){return(m.dailyStreak||0)>=3},reward:"startRelic"},
];

// Starting relic pool for unlocked rewards
var STARTER_RELICS=["zhijia","zouma","yindeng","jijiu","chenfu","moyaling"];

// --- Second boss: 墨将军 ---
// (ETYPE entry added below)
